### ISSUE TITLE
Add multi-ledger support

### ISSUE THREAD

**Issue by amanji** [openwallet-foundation/bifold-wallet#100]
AFJ has been updated with multi-ledger support. Bifold AFJ dependencies should be updated and Agent initialization should include multiple ledger configurations.

**Comment by TimoGlastra** [comment]
Adding the UI part isn't necessarily needed. By adding multiple ledger configs, AFJ can automatically determine which ledger to choose for a certain DID: https://github.com/hyperledger/aries-framework-javascript/blob/main/docs/getting-started/4-ledger.md

**Comment by amanji** [comment]
Updated the description to convey the correct fix required.
