### ISSUE TITLE
Missing credentials in proof request not being grouped properly

### ISSUE THREAD

**Issue by wadeking98** [openwallet-foundation/bifold-wallet#1011]
When receiving a proof request for firstname and last name, if the holder doesn't have the person credential then they are grouped as different credentials when they should be the same.

**Comment by jleach** [comment]
Confirmed fixed on iOS 1.0.12 1325. Both first name and last name appear on the same proof request. 

![IMG_5F7BEAFB03D7-1](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/390891/4cc4a44f-bf3a-4e5f-a6cb-4996062b0dcf)
