### ISSUE TITLE
Deeplink returns error when app times out (ios and android)

### ISSUE THREAD

**Issue by CarolineLCa** [openwallet-foundation/bifold-wallet#1019]
### Description of problem
Deeplink returns error when app times out after 5 minutes of inactivity.

### Expected behavior
It is expected that the connection via deeplink happens even if there is a timeout.

### Steps to reproduce
1. Leave the app open in background for 5 minutes
2. After that, access it using a valid deeplink
3.Enter the password and the error message will appear

The problem needs a solution for biometrics too.

### Screenshots and/or log output
![Screenshot_1698694760](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/97122568/7d9a4a0e-8520-4045-a6fb-3c0292ec5ccc)

### Environment
- [X] Occurs on Android
- [X] Occurs on iOS

**Comment by jleach** [comment]
Testing blocked by Lerna issue.

**Comment by jleach** [comment]
Fixed in 1.0.17 1744 (tested on iOS).
