### ISSUE TITLE
After accept the offer in app, the offer state is not changed to issued in Trinsic

### ISSUE THREAD

**Issue by standlove** [openwallet-foundation/bifold-wallet#102]
Hi,

After the acceptOffer method is called, the offer state becomes Requested instead of Issued. 

It works fine when accept from the Trinsic Wallet app. Can you help check if anything else is needed to make it work with Trinsic server?

Thanks.

**Comment by JamesKEbert** [comment]
We've had issues previously with the Trinsic Enterprise--do you know if you're doing a connection-less credential offer or a standard credential offer? 
Assuming the latter, the Issuer should actually issue once the credential has been requested from the Holder.

**Comment by standlove** [comment]
Hi, @JamesKEbert 

I'm not sure which one it is. I'm doing this from the trinsic UI: 
![image](https://user-images.githubusercontent.com/2214734/140004545-6fa3d740-ebfc-47da-942b-4c17f5e4c665.png)


so what if it's connection-less offer? Is there any other step needed? 

Thanks.

**Comment by standlove** [comment]
Hi, @TimoGlastra 

Sorry to bother you. If possible can you take a look at this too? 

Thank you.

**Comment by TimoGlastra** [comment]
Sure could you exactly describe the steps you're taking in both Trinsic and the Mobile wallet. From clean wallet to accepting a credential offer. Maybe I can reproduce in our wallet

**Comment by standlove** [comment]
Hi,  @TimoGlastra 

1. In trinsic
    * create a new Organization
    * generate an invitation qrcode, and then copy the URL and open the URL in a new browser window to get the unshortened url
    * Copy the unshortened URL into a qrcode generator to generate a new invitation qrcode

2. In mobile app
    * Scan the new invitation qrcode to setup the connection

3. In Trinsic again
    * Create a new credential template
    * Then select the connection and offer the credential (its state is Offered right now)

4. In mobile app again
    * Now the app will receive a notification, open it and accept the offer

5. In Trinsic again
    * You can see the credential state is changed to Requested
    * https://docs.trinsic.id/reference/issuecredential - I have to call this API manually to change the credential state to Issued

Let me know if you need more details (I can create a video if it's more helpful). Thanks for helping!

**Comment by TimoGlastra** [comment]
It may be an issue here that Trinsic thinks the request is different from the offer and therefore aborts the auto issuance?

I'll walk through the steps when I have the time.

**Comment by jleach** [comment]
As per todays Bifold WG call we're closing stale our otherwise dormant issues. Please re-open if its still relevant.
