### ISSUE TITLE
After scanning QR code, blank screen displayed

### ISSUE THREAD

**Issue by amanji** [openwallet-foundation/bifold-wallet#103]
After scanning a QR code connection a success modal is displayed. Upon unloading the modal the camera screen goes blank with no navigation triggered back to the home page.

AFJ: 0.1.0-alpha.289
Bifold: Commit cc83291ac4d579d3264181ec8890ba988116bcd7

**Comment by TimoGlastra** [comment]
Is this bug introduced with the updates to AFJ? Is the connection successfully created?

**Comment by amanji** [comment]
It looks like the connections is correctly established. I don't think the issue was introduced with AFJ updates (since I've observed the same issues before the latest update) Here is a screenshot of the workflow for accepting a VC. After the screen goes blank, I have to restart the app and I can then see the connection and notification to accept the credential. 

Update:
The issue stems from setting the `RNCamera` component to `inactive` subsequent to a connection being set, but there is no workflow to proceed after the fact (ex. navigation event, etc.) so the screen stays blank.

https://user-images.githubusercontent.com/5605464/139734435-a0ce4535-f537-4880-9251-457359b92a7f.mov

**Comment by amanji** [comment]
I believe the fix should be to navigate to the Home Screen after a scan is successful:

Here is the current block that handles code scanning:
```js
  const handleCodeScan = async (event: BarCodeReadEvent) => {
    setModalVisible('pending')
    try {
      const connectionRecord = await agent?.connections.receiveInvitationFromUrl(event.data, {
        autoAcceptConnection: true,
      })
      setConnectionId(connectionRecord.id)
      // --> Navigate back home here?
    } catch {
      setModalVisible('failure')
    }
  }
```

Or perhaps in the hook:
```js
  useEffect(() => {
    if (connection?.state === ConnectionState.Complete) {
      setModalVisible('success')
      // --> Navigate back home here?
    }
  }, [connection])
 ```
 
 Unless there is supposed to be a different workflow imitated after a connection is established.

**Comment by TimoGlastra** [comment]
I'm not too familiar with this code. Maybe @JamesKEbert or @NeilSMyers have some insights here?

**Comment by NeilSMyers** [comment]
I think putting the navigation onto the press of the "Continue" button would make more sense. Let's the user process that the action they started is now complete. And then maybe we navigate to the connections stack so they can see their new connection there.

**Comment by JamesKEbert** [comment]
Yeah this would be a workflow thing vs an AFJ issue (since the connection is being established). But yes, if you wanted to forward them to the home screen after they've connected (potentially even after a 3-5 second timeout), I'd recommend the second code block you mentioned with the useEffect:

> ``` useEffect(() => {
>    if (connection?.state === ConnectionState.Complete) {
>      setModalVisible('success')
>         // --> Navigate back home here?
>       }
>     }, [connection])
>   ```

**Comment by oznfc** [comment]
ı want to use sovring staging network and this example(https://email-verification.vonx.io/). When ı scan the Qr code my screen waiting Failure and ı must close app.I added genesis codes to ```config/ledgers/indy/indico-test-net``` . I added genesis url to env file. what is the problem ?

**Comment by amanji** [comment]
@oznfc if you're using the latest code you no longer need to specify a genesis url in the .env file. AFJ now has multi-ledger support and the mobile application is configured with both Indicio Test Net and Sovrin Staging ledgers by default (although you can add and remove ledgers based on your needs). You will still need to specify a mediator url in the .env file. Are you using the latest commit on `main`?

**Comment by oznfc** [comment]
yes ı updated again today.  I added  only 
```
GENESIS_URL= https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis
``` 
 to env file.
When ı scan the Qr code my screen waiting on ```pending``` secreen  and ı must close app. when ı opened app again. ı can see my connection on  contact screen.  error this :  normaly when scaned my qr code  by Trinsic wallet.  I'm connecting and ı 'm getting message for credential. but  ı can not getting credential message in this app.
