### ISSUE TITLE
Possibility of bypassing the PIN lock mechanism

### ISSUE THREAD

**Issue by CarolineLCa** [openwallet-foundation/bifold-wallet#1031]
### Problem 
It was identified that the number of incorrect PIN attempts is saved in the application's database, thus making it possible to bypass this control by executing an update on the database.

### Impact
An ill-intentioned user can bypass the PIN lock mechanism and execute a brute-force attack for PIN discovery.

### Evidence
![image-2023-11-16-18-10-00-218](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/97122568/5a99cc08-6298-4136-8f1d-a6eeec7c0575)

### References
https://owasp.org/www-community/controls/Blocking_Brute_Force_Attacks

**Comment by wadeking98** [comment]
@CarolineLCa do you think storing the login attempts in the keychain would solve the issue? that way it's stored in the secure enclave

**Comment by CarolineLCa** [comment]
> @CarolineLCa do you think storing the login attempts in the keychain would solve the issue? that way it's stored in the secure enclave

@wadeking98  it looks like a good idea, as this way the timeout wouldn't be exposed. I think it would solve the issue.
