### ISSUE TITLE
Failed to process revocation notification message 

### ISSUE THREAD

**Issue by himanshi4708** [openwallet-foundation/bifold-wallet#1048]
After revoking a credential from agent side, I am not receiving any notification for revoked credential on app.
Instead I am getting the following error in the console:

**WARN  WARN: Failed to process revocation notification message {
  "error": {
    "name": "AriesFrameworkError",
    "message": "Incorrect revocation notification threadId format**: \n79389b4b-efc4-425e-b951-3e5ed07ecd5f\ndoes not match\n\"indy::<revocation_registry_id>::<credential_revocation_id>\"",
    "stack": "Error\n    at captureStackTrace (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114073:32)\n    at BaseError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114111:22)\n    at construct (native)\n    at _createSuperInternal (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114012:406)\n    at call (native)\n    at BaseError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114032:26)\n    at construct (native)\n    at _createSuperInternal (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:113991:406)\n    at call (native)\n    at AriesFrameworkError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:114004:25)\n    at v1ProcessRevocationNotification$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20599:30)\n    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20624:19)\n    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)\n    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)\n    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)\n    at callInvokeWithMethodAndArg (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20641:69)\n    at v1ProcessRevocationNotification (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20534:23)\n    at invoke (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20624:19)\n    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)\n    at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)\n    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)\n    at callInvokeWithMethodAndArg (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:20624:19)\n    at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)\n   
at doResolve (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)\n    at Promise (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)\n    at callInvokeWithMethodAndArg (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:175386:82)\n    at receiveEncryptedMessage$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:4758:21)%22)  
  },
  "threadId": "79389b4b-efc4-425e-b951-3e5ed07ecd5f"
}

Can anyone help in what I might be doing wrong? @cvarjao 

I am sending the attributes in this format from agent side while hitting the revocation api:
{
  "comment": "string",
  "connection_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "cred_ex_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "cred_rev_id": "12345",
  "notify": true,
  "notify_version": "v1_0",
  "publish": true,
  "rev_reg_id": "WgWxqztrNooG92RXvxSTWv:4:WgWxqztrNooG92RXvxSTWv:3:CL:20:tag:CL_ACCUM:0",
  "thread_id": "string"
}

**Comment by jleach** [comment]
It looks like your `thread_id` value is "string" where as it should be a UUID. Try [this](https://digital.gov.bc.ca/digital-trust/showcase/) demo site. Press Command-k on a mac and you can enable revocation. Use the laywer demo and revoke it at the end to see what the correct message looks like. My though is, whatever is sending you the message, is not populating the `thread_id` correctly. 

I think you can also see a correct message format in [AIP 0183](https://github.com/hyperledger/aries-rfcs/blob/main/features/0183-revocation-notification/README.md).
