### ISSUE TITLE
Proposal for Aries Bifold to join the OpenWallet Foundation

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#1057]
At the next [Bifold UG](https://wiki.hyperledger.org/display/ARIES/Aries+Bifold+User+Group) meeting on **Jan 16th** I'll broach the subject of joining the OpenWallet Foundation (OWF). This will be an opportunity to speak in favour of, or agains the subject or just listen in. At the meeting following this, on **Jan 30th**, the maintainers can vote on the subject; should they be in favour of joining OWF, then, we will begin the process (which I'll outline on Jan 16th).

Please note that, if Aries Bifold elects to join, that outcome is not guaranteed. A favourable vote will jump-start the mechanics of the application process.

Cc. Maintainers
@amanji
@bryce-mcmath
@cvarjao 
@JamesKEbert 
@jcdrouin21 
@MosCD3 
@ryankoch13 
@thiagoromanos 
@wadeking98   

Cc. FYI
@swcurran 
@ryjones

**Comment by ryjones** [comment]
@tkuhrt

**Comment by jleach** [comment]
At [the last Aries Bifold UG meeting](https://wiki.hyperledger.org/display/ARIES/2024-01-30+Aries+Bifold+Users+Group+Community+Meeting), we ratified the decision to put forward a proposal to join the OpenWallet Foundation (OWF). PR #1089 submits said proposal for posterity. Once approved and merged, the next step will be to take the document and create a pull request against the OWF [project proposals](https://github.com/openwallet-foundation/project-proposals) and present to their technical committee.

**Comment by ryjones** [comment]
hi, @jleach . will this be a part of credo, or a distinct project?

**Comment by jleach** [comment]
> hi, @jleach . will this be a part of credo, or a distinct project?

@ryjones It will be a distinct project.
