### ISSUE TITLE
Issue with Wallet Initialization - "Error executing query: Profile not found"

### ISSUE THREAD

**Issue by tarunvadde** [openwallet-foundation/bifold-wallet#1076]
### Steps taken to solve

- Take a backup of the existing wallet.
- Import the wallet using the following lines of code:

`await agent.wallet.import(agentConfig.walletConfig, importConfig)
`
`await agent.wallet.initialize(agentConfig.walletConfig)
`

- The wallet initialization runs successfully.
- The issue occurs when trying to initialize the agent:
`await agent.initialize() // Error: "Error executing query: Profile not found"
`

### Full Code Snippet:
`// Code used for importing and initializing the wallet`
`await agent.wallet.import(agentConfig.walletConfig, importConfig)`
`await agent.wallet.initialize(agentConfig.walletConfig)`
`await agent.initialize() // Error occurs here`

**Comment by cvarjao** [comment]
@tarunvaddeSoul , have you tried using just AFJ/Credo? If you are experience the error outside of Bifold/Mobile, I would encourage you to ask the Credo (former AFJ) team: https://github.com/openwallet-foundation/credo-ts
