### ISSUE TITLE
Mediator Request was aborted due to timeout

### ISSUE THREAD

**Issue by jainavinash845** [openwallet-foundation/bifold-wallet#1082]
Hi ,
We are using Aries acapy mediator . Using the invitation URl of mediator we tried connecting Aries bifold mobile app. We are getting the following error . 
@jleach  @ryjones @cvarjao 
kindly look into this.

![image](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/44163302/aa68927f-a981-45e2-bfb5-8bbd5e3f681f)

**Comment by cvarjao** [comment]
Make sure you are using public/internet routable IP address. We are using aca-py as mediator with no problems. Have you checked if all everything is reachable? and any logs from the mobile app?
