### ISSUE TITLE
Message unpack failed

### ISSUE THREAD

**Issue by jainavinash845** [openwallet-foundation/bifold-wallet#1083]
Hi @jleach @JamesKEbert @cvarjao @ryankoch13 @thiagoromanos @wadeking98 @swcurran

In the initial while run the app changed the invitation url in the env file. And it does not redirect to wallet home page . It gives "Time out error" in the app and backend  "Message unpack failed" . Mediator is not communicating to the mobile app.
I found the backend error logs
![MicrosoftTeams-image (1)](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/44163302/76a43900-4b2b-4a30-931e-0d7c6b97403b)
Please let me know , how can resolve it.

**Comment by jleach** [comment]
I think no supported transports means there is no websocket for it to send a message on. When the wallet starts make sure tou see it establish a wss connection in the logs.

**Comment by jainavinash845** [comment]
Hi @jleach 

Earlier it was working fine. we were able to establish a connection between mediator and mobile, web socket transport was also working.
Now after building new images .I pasted my invitation URL in mobile application and it is not working.
![Uploading InkedMicrosoftTeams-image.jpg…]()

**Comment by jainavinash845** [comment]
Hi @jleach

Earlier it was working fine. we were able to establish a connection between mediator and mobile, web socket transport was also working.
Now after building new images .I pasted my invitation URL in mobile application and it is not working.
file: start.sh

![image](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/44163302/e97d9b30-a1c6-4db9-bd2a-73cc804e4316)

Please let me know , how can resolved it.

**Comment by cvarjao** [comment]
closing stale issues
