### ISSUE TITLE
No corresponding recipient key found in ('BeJExxxxxxxxxxxxxxxxxxxxxxxx') and Message Unpack failed

### ISSUE THREAD

**Issue by jainavinash845** [openwallet-foundation/bifold-wallet#1085]
Hi @jleach @JamesKEbert @WadeBarnes @wadeking98 @cvarjao @ryankoch13 @thiagoromanos @swcurran

I am using acapy mediator. After getting invitation url and paste it into application , it does not communicate , getting Error.
![image](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/44163302/f22397a2-03a3-4377-bfb1-5bbe8e04bb43)

and this is start.sh file
![MicrosoftTeams-image](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/44163302/12fae3e9-d6af-4efd-abc8-117f3a36586a)
Please look into it and how can resolve it .

**Comment by cvarjao** [comment]
@jainavinash845, based on the logs, this looks like a question for aca-py - https://github.com/hyperledger/aries-cloudagent-python
