### ISSUE TITLE
Group messaging query

### ISSUE THREAD

**Issue by RazinRahat** [openwallet-foundation/bifold-wallet#1087]
### Description of problem
In existing bifold wallet, 2 devices can be connected with each other through QR code. Now our query, does this system has any existing feature or way that can connect 3 or more devices through QR code and build a group messaging system like popular social media Whatsapp or Messenger's group chat feature. Is it possible for the current bifold wallet?

### Development Environment
- [ ] Android
- [ ] Linux

**Comment by cvarjao** [comment]
@RazinRahat, we leverage DIDComm protocol for messaging, and as far as I am aware there is no support for group messaging. I would encourage asking the folks working on DIDComm - https://github.com/decentralized-identity/didcomm-messaging
