### ISSUE TITLE
Propose adding the requirement for semicolon in code

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#114]
This requested project improvement is to add back eslint/prettier rules to require the use of semicolons.

While Automatic Semicolon Insertion (ASI) is great and pretty reliable I find its more common in ECMAscript based languages to add semicolon in rather than rely on the implementations in the JS interpreter (which are quite day in most implementations). Also, I believe they are require by the ECMAscript standard but as a convenience they are permitted to be omitted so longs as ASI is implemented in the interpreter.

**Comment by TimoGlastra** [comment]
We've had a discussion about it in AFJ: https://github.com/hyperledger/aries-framework-javascript/pull/224 and I applied the same rules to this repository to keep consistency between the projects. I think it would be great if we can keep some consistency between the projects.

But if the overall preference of the other maintainers is leaning towards using semicolon, fine by me 👍
