### ISSUE TITLE
Font selection and saving it Wallet App setting

### ISSUE THREAD

**Issue by nbAmit** [openwallet-foundation/bifold-wallet#122]
Can we have options in settings screen where user can set the custom fonts and also scale the font size as well?

**Comment by jleach** [comment]
Hi @nbAmit Do you think users will want to select fonts / sizes? I've looked through a few lager apps (Instagram, LinkedIn) and they don't appear to let the user select fonts. Rather, they appear to use the default font or one of their own choosing.

**Comment by nbAmit** [comment]
Here is one of the approach we can think of

![ezgif com-gif-maker](https://user-images.githubusercontent.com/91456036/142218625-579a8954-03ba-4f08-ab75-b980cff56b85.gif)

**Comment by jleach** [comment]
As per todays Bifold UG/WG call we're closing stale issues. Please re-open if this issue is still relevent.
