### ISSUE TITLE
Init agent bug

### ISSUE THREAD

**Issue by MosCD3** [openwallet-foundation/bifold-wallet#1271]
### Description of problem
@jleach I spotted a bug after your PR #1258 
Whenever you start the wallet, you always hit this error
Screen shot
The reason for that is basically the useEffect hook is being fired on re-render, something on the deps array changed I guess
And it always hit the guard (if statement) that you introduced, which causes an exception to fire when the wallet is already initialized
Would you please take a look

### Expected behavior
Wallet to initialize without errors

### Steps to reproduce
Launch the app
### Screenshots and/or log output
![Simulator Screenshot - iPhone 16 - 2024-10-02 at 10 37 29](https://github.com/user-attachments/assets/7dc87456-bb18-4811-a704-ad16d69a0db5)
![Screenshot 2024-10-02 at 10 42 56 AM](https://github.com/user-attachments/assets/25fd0134-93fd-4135-8b05-d7ba3835d89f)

### Environment
- [ ] Occurs on Android
- [ ] Occurs on iOS

Build #:

Android Device Model: 

iOS Device Model: 

### Severity
- [ ] High
- [ ] Medium
- [ ] Low

**Comment by jleach** [comment]
@MosCD3 I've added a check to treat an open wallet as a warning since its not really an error IMHO. But, you might want to check why your wallet is not being closed between PIN entries. If its Bifold then we can create a separate issue to look there.
