### ISSUE TITLE
Add support for BCovrin Test and CANdy Dev ledgers

### ISSUE THREAD

**Issue by ianco** [openwallet-foundation/bifold-wallet#128]
Genesis url:  http://test.bcovrin.vonx.io/genesis

This network is used by a lot of test/demo apps

**Comment by jleach** [comment]
@ianco In PR #101 @amanji added support for the Sovrin Staging ledger. Is this a different ledger?

**Comment by jleach** [comment]
@ianco NM. Must be different, the genesis files differ.

**Comment by WadeBarnes** [comment]
Genesis url for CANdy Dev is: https://github.com/ICCS-ISAC/dtrust-reconu/blob/main/CANdy/dev/pool_transactions_genesis
