### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by manghuli** [openwallet-foundation/bifold-wallet#137]
- remove emotion library
- revert styles accordingly
- extend globalStyles file as needed

**Comment by TimoGlastra** [comment]
~~Why do you want to remove the emotion library, I thought they were just added? I don't have a specific preference myself, but just curious why we're reverting~~

nevermind, just saw your message in Rocket.Chat

**Comment by jleach** [comment]
As per todays Bifold UG/WG call we're closing stale issues. Please re-open if you feel strongly its still an issue and relevent.
