### ISSUE TITLE
Create new on-boarding screens

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#147]
When implemented this feature will allow the application to show a carousel of on-boarding training screens. They will only be displayed once and their content will be customizable. See [these mock designs](https://xd.adobe.com/view/93c2d0e1-081a-4f62-b358-4e3d9b9a8847-c691/grid/) to better understand how it will be presented when done.

**Comment by alexgmetcalf** [comment]
There are several small issues which I can raise and add as dependencies (and assign to me) once this issue gets moved to the right repo.

**Comment by knguyenBC** [comment]
This is technically done right? Any minor issues or updates to the onboarding is already either a new ticket or new issue.

**Comment by jleach** [comment]
Should be. Content and graphics are updated. Anything else should be a new issue.

Regards,

Jason Leach
