### ISSUE TITLE
Terms and Conditions screen

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#148]
As a User I want to review the terms and conditions screen
So that I understand my legal obligations when using the app

Scenario: User Accepts Terms

Given The User has completed the on-boarding carousel screens
And User sees the Terms and Conditions screen
When The User scrolls to the bottom of the screen
And The users accepts the Terms and Conditions
And The continue button becomes active 
And The user clicks continue
Then The user transitions to the PIN creation screen

Scenario: User Rejects Terms

Given The User has completed the on-boarding carousel screens
And    User sees the Terms and Conditions screen
When The User scrolls to the bottom of the screen
And The User presses the back button
Then The User goes back to the **last** on-boarding screen they viewed.

**Comment by jleach** [comment]
Looking at doing this in HTML because it'll be pretty touch to get the styling working as shown in the screen designs. [This](https://www.npmjs.com/package/react-native-render-html) looks like a promising npm package.

**Comment by jleach** [comment]
This feature cannot be "Done" 100% because we don't have a ToS to use. We'll need the Lawers to craft one.

**Comment by nodlesh** [comment]
@jleach The final statement in the first scenario doesn't match the wireframes, should
Then The user transitions to the PIN creation screen
be
Then the user transitions to the secure your wallet screen?

**Comment by nodlesh** [comment]
Another question on this.  For this scenario:
```gherkin
Scenario: User Rejects Terms

Given The User has completed the on-boarding carousel screens
And User sees the Terms and Conditions screen
When The User scrolls to the bottom of the screen
And The User presses the back button
Then The User goes back to the last on-boarding screen they viewed.
```
If during onboarding they pressed skip, say on the second onboarding page, if they clicked back on the Terms page, would they go back to the second onboarding page or restart the onboarding?

**Comment by nodlesh** [comment]
This Story has been tested and the test automated in AMTH. 
You can see the behavioural specification here, https://github.com/hyperledger/aries-mobile-test-harness/blob/main/aries-mobile-tests/features/bc_wallet/terms.feature

**Comment by nodlesh** [comment]
I can't seem to move this to done.

**Comment by alexgmetcalf** [comment]
Issues:
- Checkbox at the bottom has mixed tenses. I suggest either: "I have read, understood and accepted the terms and conditions." or "I have read, and understand and accept, the terms and conditions."
- Scroll indicator isn't visible on iOS when you scroll down. (Minor issue but would help get sense of scale of content.)
- There are small EULA text updates coming.

**Comment by nodlesh** [comment]
@alexgmetcalf  Scroll indicator is working for me on iOS. iPhone 6s. iOS 15.3.

Should the other issues be logged as separate and set this to done?

**Comment by alexgmetcalf** [comment]
> @alexgmetcalf Scroll indicator is working for me on iOS. iPhone 6s. iOS 15.3.
> 
> Should the other issues be logged as separate and set this to done?

Not visible on iPhone 8, iOS 15.2.1. For clarity, I'm talking about the visual scroll bar position indicator that usually appears on the right once you start scrolling.

**Comment by nodlesh** [comment]
@alexgmetcalf I believe you, honestly. 😉

iPhone 6s with 15.3
![IMG_A4357B48E753-1](https://user-images.githubusercontent.com/44370861/155414779-9dd0b027-a5ee-4c9a-9d00-1e6dd786ac45.jpeg)

iPhone 8 with 15.0.1
<img width="615" alt="Screen Shot 2022-02-23 at 4 50 36 PM" src="https://user-images.githubusercontent.com/44370861/155414863-f779b1e3-83f2-4774-b0ba-352b69840ff4.png">

**Comment by alexgmetcalf** [comment]
Haha well, weird.
