### ISSUE TITLE
Connections list

### ISSUE THREAD

**Issue by amanji** [openwallet-foundation/bifold-wallet#154]
Currently the Connections list is a basic flat-list that shows the name of the Issuer, the public DID and the date added. Proposed enhancements:

* Tap to show more details of connection
* Swipe to delete/remove connection
* Branding/theming and logo addition (pending community standardization of Credential/Connection display)

**Comment by amanji** [comment]
Need accompanying wireframes

**Comment by amanji** [comment]
Screenshots of potential UI/UX for discussion

<img width="378" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/5605464/143930207-6146837d-7658-494d-8f53-ef8625b9ef2f.png">
<img width="378" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/5605464/143930210-dcded9d3-f29e-47a7-a9d4-8514c52753dc.png">
<img width="378" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/5605464/143930211-f79d6d28-787f-4834-a97b-1a9fbec839ca.png">
<img width="378" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/5605464/143930212-d9af0bbd-3db7-4b4b-8d55-6a08d1d1175c.png">

**Comment by darrellodonnell** [comment]
does "swipe to delete connection" also delete the credentials that were issued across that connection? This may be desirable - but also may need to be considered case-by-case. 


Consider two use cases:

- A credit union credential may require the connection to be fully functional (e.g. credential can be used in isolation, but usually it is part of a flow that ends up prompting the member to confirm something over the DIDComm channel). This particular case implies deletion of related credentials when connection is deleted.
- A government ID credential may be useful by itself and the citizen may want to explicity delete the connection but maintain the ability to use the credential. In this case we wouldn't want to delete the credential with the connection.

**Comment by amanji** [comment]
I hadn't considered the first use case, more the second where a credential could be kept after the connection is severed. So swipe to delete would really just remove the connection.

**Comment by amanji** [comment]
Workflow linked: https://lucid.app/lucidchart/e1b8b454-5652-44ca-9345-fadf80cf20ff/edit?invitationId=inv_b4ac42d1-dae2-4ae2-8f01-f4f8f32bcf49&page=0_0#

**Comment by knguyenBC** [comment]
Can't update this ticket for some reason but updates to the new Connection list: https://xd.adobe.com/view/be5d6531-658b-4d7c-8ec2-634825d724fe-eb0e/
