### ISSUE TITLE
indy-sdk-react-native as declared dependency instead of vendoring 

### ISSUE THREAD

**Issue by cvarjao** [openwallet-foundation/bifold-wallet#156]
As per Twelve-Factor App methodology, switch to "Explicitly declare and isolate dependencies" to "declares all dependencies, completely and exactly, via a dependency declaration manifest"

**Comment by TimoGlastra** [comment]
I'm not 100% sure what you mean by this issue. Could you elaborate a bit @cvarjao?

**Comment by cvarjao** [comment]
It is about getting `indy-sdk-react-native` packaged/published (maybe using CocoaPods?), instead of copying the files to `ios/Pods/Frameworks/Indy.framework`

**Comment by TimoGlastra** [comment]
Ah makes sense. That would be really great! Are you going to package the indy binaries with the package, or going to install them with some post install script?

**Comment by cvarjao** [comment]
I just create the issue so I can get somebody else looking into it :D I am not an iOS developer. But, I think it might require some work on the Indy repository side to do the publishing. Hopefully, we can leverage CocoaPods dependency management to take care of the fetching/installing as opposed to the hacky custom download/extract post install script I've introduced for Android. But similar along the lines where the dependency is declared and somewhat installed.

**Comment by jleach** [comment]
Going to close this one. The work @TimoGlastra is doing to move AFJ towards ASKAR will make this issue irrelevant. The's already created several tickets to track this work. See #617 for more information.
