### ISSUE TITLE
Feature request - Change mediator connection

### ISSUE THREAD

**Issue by ianco** [openwallet-foundation/bifold-wallet#157]
Currently the mediator invitation is bundled with the release in an `.env` configuration file.

I'd like the ability to dynamically connect to a new mediator after I've installed the app, i.e. connect to a new agent and then flag this new connection as the Mediator connection.

Not sure if others are interested in this feature, but currently the mediator is bundled into the release and then (as far as I can tell) can't be changed.

In a developer scenario (or if I'm debugging integration issues between agents), I'd like to start my own mediator and then connect my mobile app to my mediator, that way I can see the full message flows.

**Comment by jleach** [comment]
As per todays Bifold WG call we're closing stale our otherwise dormant issues. Please re-open if its still relevant.
