### ISSUE TITLE
Incorporate overlays (OCA) to support internationalization

### ISSUE THREAD

**Issue by ianco** [openwallet-foundation/bifold-wallet#164]
See https://hackmd.io/3sKnm7v7R_mo6or3TFFsfQ

**Comment by flihp27** [comment]
Just to share our team is working on this issue.

Here is our proposition that where working on: https://github.com/ICCS-ISAC/vc-wallet-portefeuille/issues/1

**Comment by jleach** [comment]
Duplicate of #164.
