### ISSUE TITLE
Sovrin BuilderNet and Mediator

### ISSUE THREAD

**Issue by dukmarques** [openwallet-foundation/bifold-wallet#168]
Hi, I'm trying to use the project through the Sovrin BuilderNet network (since StagingNet is now paid).
I'm uploading an Aca-Py instance locally as a mediator and generating a connection invitation. When passing the invitation in the .env file, I've been getting the following errors when running the project on my mobile:

```

ERROR: Message is undeliverable to connection f16b3b58-e22d-4b24-a72a-0ede9169d174 (Mediator Builder)

....

 WARN Possible Unhandled Promise Rejection (id: 0):
[AriesFrameworkError: Message is undeliverable to connection f16b3b58-e22d-4b24-a72a-0ede9169d174 (Mediator Builder)]
 DEBUG DEBUG: Request was aborted due to timeout. Not throwing error due to return routing on sent message
 DEBUG DEBUG: No response received.
```

Would you like to know if the project supports Sovrin's BuilderNet network? (since it is now the only free sovrin for testing)

Is there any public mediator for sovrin's networks (mainly BuilderNet) like Indicio's (https://indicio-tech.github.io/mediator/)?

My commands to start Aca-Py as a mediator:
```

sudo PORTS="7021 7020" ./scripts/run_docker start --endpoint http://004b-177-134-247-168.ngrok.io --inbound-transport http 0.0.0.0 7020 --outbound-transport http - -admin 0.0.0.0 7021 --admin-insecure-mode --wallet-type indy --wallet-name demoapp --wallet-key ****** --preserve-exchange-records --auto-provision -- genesis-url https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_builder_genesis --trace-target log --trace-tag acapy.events --trace-label dev.Agent.trace -- auto-accept-invites --auto-accept-requests --auto-store-credential --label dev.Agent --seed 000000000000000000000000MEDIATOR --open-mediation --emit-new-didcomm-prefix
```

I also created a folder in configs>ledgers>indy called sovrin-builder-net with the files genesis-file (containing genesis from buildernet) and pool-config, according to others.

This is the entire process I'm currently using to try to run the project on the Sovrin BuilderNet network, any tips that might help I'm grateful!

**Comment by jleach** [comment]
Closing stale issues as per July 19 Bifold UG call. Please re-open if unresolved or if its still relevant.
