### ISSUE TITLE
No message class found for message type "https://didcomm.org/issue-credential/2.0/offer-credential"

### ISSUE THREAD

**Issue by ripulbd** [openwallet-foundation/bifold-wallet#182]
Hi,

I am using the Aries React Native Mobile Agent. I am having this peculiar issue which I did not have previously. When I received a credential from an agent, the credential is not being shown to the App. Instead I can see this error message in the console: "[AriesFrameworkError: No message class found for message type "https://didcomm.org/issue-credential/2.0/offer-credential"]"

I can even see the received credentials (see the attached screenshot), but I cannot accept the credential. What could be the issue for this message? 
![Screenshot from 2022-01-26 16-55-44](https://user-images.githubusercontent.com/1178467/151199316-239e36ae-79d3-47e3-80a9-cb131a4803e6.png)

Thanks in advance for any lead.

Regards,
Ripul

**Comment by ripulbd** [comment]
Hi,

The main issue is was that the agent was sending V2 offer, however, AFJ current supports only V1. The mismatch resulted in that particular error. You can close this issue. Thank you.

**Comment by jleach** [comment]
Lots of V2 is now supported as we just updated to AFJ 0.2.0. If the problem persists please open the issue again with any additional details. 

Closing stale issues as per July 19 Bifold UG call. Please re-open if unresolved or if its still relevant.
