### ISSUE TITLE
rename to aries-mobile-agent-react-native

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/bifold-wallet#19]
This is really nit-picky but I'd like to propose to change the name from `aries-mobileagent-react-native` to `aries-mobile-agent-react-native`. It looks a lot cleaner IMO. This is also what we did for our mobile agent.

It are two separate words and I'm not sure why all other aries projects do it.

If people disagree I'm fine with keeping it as is, I just wanted to have made my case.

**Comment by JamesKEbert** [comment]
I agree with this and it's what I had initially proposed internally, however we decided to go with what everyone else had already done. So, I am in favor of this, but I'd like to hear @TelegramSam's thoughts though.

**Comment by TelegramSam** [comment]
I'm not passionate about either name. You two are the main contributors to the project at this point, and I'm happy with either choice.

**Comment by JamesKEbert** [comment]
Cool, I will make this change prior to talking to Ry Jones today in getting this transferred to Hyperledger.
