### ISSUE TITLE
No working in Android

### ISSUE THREAD

**Issue by jmerino12** [openwallet-foundation/bifold-wallet#211]
i have an error when i run in android.

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/jonathan/Documents/aries-mobile-agent-react-native/android/settings.gradle'

* What went wrong:
Could not compile settings file '/Users/jonathan/Documents/aries-mobile-agent-react-native/android/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
  
  java.lang.IllegalArgumentException: Unsupported class file major version 61

**Comment by jleach** [comment]
@jmerino12 I think the issue is specific to your environment. Check the [GitHub Actions](https://github.com/hyperledger/aries-mobile-agent-react-native/blob/main/.github/workflows/main.yaml). It does an Android build for every PR or merge to main and it runs ok.

**Comment by jmerino12** [comment]
@jleach  yes, configure correctly and it already worked for me, thanks
