### ISSUE TITLE
Is there a publicly available mediatorUrl i can use?

### ISSUE THREAD

**Issue by ILoomans** [openwallet-foundation/bifold-wallet#24]
Hello, 

Is there a publicly available mediatorUrl i can use to test the app? The one i am hosting locally doesnt seem to be working as the connection with the mediator stays on requested.

Just as a background, I am demoing this app with the aca-py demo faber agent to create a connection and issue credentials, I am able to establish a connection with the mediator and faber agent, but when i issue credentials from the faber agent and go to the credentials page on the app i get an Mediation error.

Mediation Error:  503 ngrok gateway error
The server returned an invalid or incomplete HTTP response.

Ignace Loomans

**Comment by JamesKEbert** [comment]
Hi Ignace!

As of right now there is not a publicly available Aries Framework Javascript (AFJ) mediator as far as I am aware, unless @TimoGlastra knows of one from the AFJ point of view. 

Right now Indicio's efforts are finishing the [coordinate mediation protocol](https://github.com/hyperledger/aries-rfcs/blob/master/features/0211-route-coordination/README.md) support, which would allow it to use a public mediator, such as [Indicio's test mediator](https://indicio-tech.github.io/mediator/) or other mediators that support the protocol. 

We've had some issues with the RN hot reloading, so one of my first troubleshooting suggestions would be to uninstall the app and re-compile the App, which should guarantee you're using the correct mediator URL.

**Comment by ILoomans** [comment]
Hey James,

Thanks for the response, there is a publicly available mediator on AFJ, they have some nice instructions on how to run it, and you are right, today it for some reason worked, which is nice! This is a really neat project you guys are working on.

Ignace Loomans
