### ISSUE TITLE
Running on MacOS Apple Silicon

### ISSUE THREAD

**Issue by drewcapener** [openwallet-foundation/bifold-wallet#248]
Hi, I've just been familiarizing myself with some of the repos in the Aries project. I wanted to try and install and run the mobile agent but haven't been able to get it to run (trying for ios) on my apple silicon Mac by following the provided instructions. I am assuming my issues must be coming from the different architecture but it may be something else as well. Has anyone been able to get this running or does anyone have any thoughts as to how I might approach getting it running? I'm happy to provide further details (errors, etc.) if that would be helpful. Thanks in advance!

**Comment by amanji** [comment]
Are you trying to run it in an iOS simulator?

**Comment by drewcapener** [comment]
Hey @amanji thanks for being willing to help out. I got it working. Still not sure what the problem was though. I ended up undoing and then redoing the entire install and somehow it fixed it.
