### ISSUE TITLE
How could I get offered credentials?

### ISSUE THREAD

**Issue by ILoomans** [openwallet-foundation/bifold-wallet#29]
Im finding the listener for the state changing in credentials to be a bit unreliable at the moment. I would like to add a refresh button to find new offered credentials. Does anyone by chance know how I could fetch all offered credentials for my agent?

So instead of using this 
`
     agentContext.agent.credentials.events.removeAllListeners(CredentialEventType.StateChanged)
      agentContext.agent.credentials.events.on(CredentialEventType.StateChanged, handleCredentialStateChange)
`

Have a button that onPress I can fetch the offered credentials for my existing connections. 

Thanks allot!

**Comment by TimoGlastra** [comment]
Not possible at the moment, but should definitely be possible. This is more a limitation of Aries Framework JavaScript than the mobile agent however. Can you open this issue over there?

**Comment by ILoomans** [comment]
Sorry I will close this issue, the problem wasnt with the mobile app but with my aca-py demo.

**Comment by TimoGlastra** [comment]
We already have query methods, but they don't store state at the moment. What other parameters would you like to query on?
