### ISSUE TITLE
New app architecture !!

### ISSUE THREAD

**Issue by MosCD3** [openwallet-foundation/bifold-wallet#301]
Hi Devs
Its really confusing, having 2 App.tsx files and the new App architecture seems confusing a bit
Is there any document that shows the app new folder architecture and why is there 2 App.tsx files

I can't even seem to get my code to work trying to modify files (Adding security providers ) then running the app and it still doesn't reflect my changes

It would be great to have a documentation for contributors guiding them through for doing any changes

**Comment by amanji** [comment]
Id suggest making a pull request to update the official [AFJ docs](https://aries.js.org):

https://github.com/hyperledger/aries-javascript-docs
