### ISSUE TITLE
Unable to run the agent on Linux machine

### ISSUE THREAD

**Issue by realabbas** [openwallet-foundation/bifold-wallet#333]
I'm trying to run the agent on linux machine but I'm unable to do so.

The error occurs while installing dependencies `npm install`

`@commitlint/cli not accessible from aries-bifold`

Error Screenshot

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/43527087/170008936-f0faeac2-7057-4847-8b08-00f09da2c49a.png)

I've tried setting up the project and it works on the windows and mac machine

**Comment by wYaobiz** [comment]
You can try use `sudo` or run under root

**Comment by JamesKEbert** [comment]
Hi @realabbas, I've also run into this issue--I've only been able to get it to work by running `npm install --legacy-peer-deps` inside of `./core` and then again inside of `./app`, which is not exactly ideal. 

cc: @cvarjao

**Comment by cvarjao** [comment]
What version of npm are you using? There has been some breaking changes to newer npm

**Comment by JamesKEbert** [comment]
Currently 8.12.1

**Comment by cvarjao** [comment]
I recommend using node 16.15.0 with npm 8.5.5.  That is what we are using to test in GH Actions, I've had issues with newer npm. I don't know if it is worthwhile fix those npm issues, or just do the work to switch to yarn.

**Comment by JamesKEbert** [comment]
I think yarn as a base is a good idea--however often many libraries support both, so it may be worth creating an issue/work item to address the npm issues?

**Comment by jleach** [comment]
As per todays Bifold WG call we're closing stale our otherwise dormant issues. Please re-open if its still relevant.
