### ISSUE TITLE
Invalid QR Code. Please try again.

### ISSUE THREAD

**Issue by drewcapener** [openwallet-foundation/bifold-wallet#335]
Whenever I try to scan a QR code I am met with a message popping up that says, "Invalid QR code. Please try again." Not sure why this is happening, but I must be missing something simple. I'd be very grateful for any help.

iOS 15.4.1

**Comment by JamesKEbert** [comment]
I am currently able to reproduce this--I haven't got any helpful logs yet though (likely due to iOS oddness), but I don't think you're crazy :)
@ryanindicio are you able to look into this?

**Comment by drewcapener** [comment]
@JamesKEbert @ryanindicio I just wanted to check in and see if any progress has been made here?  The problem still seems to be occurring in iOS 15.5. Is the whole iOS side of things broken?
*Still occurring barring anything having been done to fix it, in which case I probably just need to pull down the latest.

**Comment by cvarjao** [comment]
closing stale issues
