### ISSUE TITLE
Unable to run npm install as per the instructions in the README

### ISSUE THREAD

**Issue by github-account-0x00** [openwallet-foundation/bifold-wallet#347]
Errors as per screenshot, running on intel macos

![Screenshot 2022-06-03 at 11 54 23 AM](https://user-images.githubusercontent.com/63097716/171783025-02650b48-2498-45f8-bb28-228605edd9df.png)

**Comment by swcurran** [comment]
@amanji could you take a look at the ReadMe to see if there is something missing?  Thanks!

**Comment by amanji** [comment]
Try to run the install command with the `--force` flag: `npm install --force`. It's typically the only way I can resolve module installation until we clean up dependencies a bit better.

**Comment by github-account-0x00** [comment]
> Try to run the install command with the `--force` flag: `npm install --force`. It's typically the only way I can resolve module installation until we clean up dependencies a bit better.

I tried using that and encountered the following error:

![Screenshot 2022-06-09 at 11 37 53 AM](https://user-images.githubusercontent.com/63097716/172759208-0ddb0a23-aab8-494f-bccb-669ea647a500.png)

![Screenshot 2022-06-09 at 11 37 33 AM](https://user-images.githubusercontent.com/63097716/172759219-f773e150-6851-41eb-b15a-680851ffdfa0.png)

**Comment by cvarjao** [comment]
what version of node/npm are you using?
```
$ npm version
{
  npm: '8.5.5',
  node: '16.14.2',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1n+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```
make sure you are using node 16+, npm 8+

**Comment by github-account-0x00** [comment]
> what version of node/npm are you using?
> 
> ```
> $ npm version
> {
>   npm: '8.5.5',
>   node: '16.14.2',
>   v8: '9.4.146.24-node.20',
>   uv: '1.43.0',
>   zlib: '1.2.11',
>   brotli: '1.0.9',
>   ares: '1.18.1',
>   modules: '93',
>   nghttp2: '1.45.1',
>   napi: '8',
>   llhttp: '6.0.4',
>   openssl: '1.1.1n+quic',
>   cldr: '40.0',
>   icu: '70.1',
>   tz: '2021a3',
>   unicode: '14.0',
>   ngtcp2: '0.1.0-DEV',
>   nghttp3: '0.1.0-DEV'
> }
> ```
> 
>  make sure you are using node 16+, npm 8+


Here is the version of nodejs that I am using:
![Screenshot 2022-06-09 at 12 10 28 PM](https://user-images.githubusercontent.com/63097716/172762519-573a8784-2e94-4798-ae7a-79a7552d1fed.png)

**Comment by cvarjao** [comment]
It seems to be a problem with recent npm, can you downgrade to npm 8.5.5?

**Comment by nayrban** [comment]
the node version `16.14.2` works just fine!
