### ISSUE TITLE
Any experience managing proof requests with the verifier agent?

### ISSUE THREAD

**Issue by ILoomans** [openwallet-foundation/bifold-wallet#36]
Hello,

After receiving credentials from the issuer agent, I have established a connection with the verifier agent, and am now trying to send a proof request. After the connection is established my backend sends a present-proof id message to the established connection. And after this I am supposed to 'present the proof' from the mobile side. I was just wondering if this area has already been covered in the app, or if its something that i will have to implement myself! Thanks in advance.

**Comment by JamesKEbert** [comment]
Hello! Sorry for the delay in response--been heads down working.

Currently we're working on this--I expect to have this added soon. As a clarification, we're focusing on Android, relying on the initial efforts by @karimStekelenburg and any others. There are some additions needed in [rn-indy-sdk](https://github.com/AbsaOSS/rn-indy-sdk) to do presentations in iOS though. [This](https://github.com/AbsaOSS/rn-indy-sdk/commit/079e8d3217efe15a81652db03e8400575be34377) is the relevant commit that added the needed functionality for Android. We can add this needed functionality, but it's not my first priority. Is this something you'd be interested in helping with @ILoomans ?

**Comment by jleach** [comment]
As per todays Bifold UG/WG call we're closing stale issues. Please re-open if you feel strongly its still an issue and relevant.
