### ISSUE TITLE
Black Screen On Run

### ISSUE THREAD

**Issue by drewcapener** [openwallet-foundation/bifold-wallet#364]
I created the previous issue #335 a couple of weeks ago. I haven't made headway on it myself and haven't seen any notable activity. This week, I pulled down the latest to see if the issue remained and now have a new issue where the app launches to merely a black screen where before it would at least show the app. I am wondering if this is something specifically wrong with my configuration or if it is a general issue and whether or not anyone has dealt with the problem before.

MacOS Monterey 12.4 on x86
XCode 13.3.1
iPhone 11 running iOS 15.5

I am seeing several warnings but no errors at Buildtime and no further logs

**Comment by amanji** [comment]
Was there any resolution to this?

**Comment by cvarjao** [comment]
closing stale issues
