### ISSUE TITLE
How to update the ''ListCredentials'' component after removing a credential?

### ISSUE THREAD

**Issue by pabacouros** [openwallet-foundation/bifold-wallet#371]
Hello, I am developing the functionality to remove a credential from the wallet ('RemoveFromWallet') and I would like to ask you the following:

How to update the ''ListCredentials'' component after removing a credential?

For example:
```js
const removeFromWallet = async (credential: CredentialRecord) => {
    try {
      const id = credential.id || credential.credentialId
      await agent?.credentials.deleteById(String(id))
      navigation.getParent()?.navigate(TabStacks.CredentialStack, { screen: Screens.Credentials })
      // -->> how to update the 'ListCredentials' component here? <<--
    } catch (e: unknown) {
      Toast.show({
        type: ToastType.Error,
        text1: t('Global.Failure'),
        text2: (e as Error)?.message || t('CredentialOffer.CredentialNotFound'),
      })
    }
  }
```
Image reference:
<img width="1141" alt="Screen Shot 2022-07-13 at 16 19 00" src="https://user-images.githubusercontent.com/107563305/178838241-efc1ebda-cee7-44e4-98b3-9622e1117c66.png">

**Comment by amanji** [comment]
Hi @pabacouros, with the upcoming update to the AFJ react-hooks extension used by the wallet, you shouldn't need to update the list as the `useCredentials` hook will automatically update its internal record list when credentials are added/updated/removed. Previously hooks only responded to record updated changes.

**Comment by pabacouros** [comment]
Thank you! @amanji
