### ISSUE TITLE
Can not present proof with "non-revoke" in proof request

### ISSUE THREAD

**Issue by DucDA177** [openwallet-foundation/bifold-wallet#372]
When I create a proof request from aca-py, the mobile agent receive the request but stuck at "Fetching Credential Revocation Status for Credential Revocation Id '8' with revocation interval with to '1657784360' & from '0'"
Here is the log of mobile agent: 
` ----LOG  TRACE: Presentation is requesting proof of non revocation for referent 'Voucher', getting revocation status for credential {
  "requestNonRevoked": {
    "from": 0,
    "to": 1657784360
  },
  "credentialRevocationId": "8",
  "revocationRegistryId": "Qcpd4QqtF4x1hzNQUK75LF:4:Qcpd4QqtF4x1hzNQUK75LF:3:CL:49681:voucher 2.0:CL_ACCUM:fdb348ec-af04-4b51-8562-4583a45af938"
} 
 --------LOG  TRACE: Fetching Credential Revocation Status for Credential Revocation Id '8' with revocation interval with to '1657784360' & from '0'` 

and the mobile display the message like this: 
![image](https://user-images.githubusercontent.com/48557721/178929545-65753a3c-1d8f-4c1b-a2bb-45c58908e967.png)

Here is the proof request I created from aca-py agent:
`{
  "auto_verify": true,
  "comment": "need to verify",
  "connection_id": "6bc8ac7d-0c1f-48c5-924d-412bf09f807c",
  "proof_request": {
  "name": "Voucher",
  "version": "2.0",
  "requested_attributes": {
    "Voucher": {
      "names": [
        "name",
        "dob"
      ],
      "restrictions": [
        {
          "schema_id": "Qcpd4QqtF4x1hzNQUK75LF:2:voucher:2.0"
        }
      ]
    }
  },
  "requested_predicates": {
    "Voucher 0": {
      "p_type": ">",
      "p_value": 50,
      "name": "discount",
      "restrictions": [
        {
          "schema_id": "Qcpd4QqtF4x1hzNQUK75LF:2:voucher:2.0"
        }
      ]
    }
  },
  "non_revoked": {
    "from": 0,
    "to": 1657784360
  }
},
  "trace": true
}`

**Comment by duongtranfu** [comment]
Same issue here! could you please help @amanji

**Comment by cvarjao** [comment]
@amanji, I vaguely remember we had issues with the from `0` revocation range. Was that fixed in AFJ?

**Comment by cvarjao** [comment]
closing stale issues
