### ISSUE TITLE
Development PNG Images on Android

### ISSUE THREAD

**Issue by JamesKEbert** [openwallet-foundation/bifold-wallet#373]
While developing, we've run into an issue of PNGs not displaying while running Android in development (in particular in the `./core` package). SVGs appear to still work as expected. 

I experimented a lot with the metro bundler and react native config to no avail as of yet. Any insight here @cvarjao?

**Comment by cvarjao** [comment]
@JamesKEbert , got an example on how PNG is being used?

**Comment by JamesKEbert** [comment]
If on the `./core/App/screens/PinEnter.tsx` screen you change the <Image> source:
```
<Image
   source={require('../assets/img/logo-large.png')}
```
And you can change the png to any png in the `./core/App/assets/` directory you want, it won't show up during development. 

(or were you looking for a branch?)

**Comment by leteu** [comment]
I had the same problem, I saw that the image show when I call image to uri.

It seems to be a path issue in Android.

ex) 
`
<Image
        source={{
          uri: 'https://i.ibb.co/qF8qRnK/upload-1.png',
        }}
        resizeMode="cover"
        style={{ height: 100, width: 100 }}
/>
`

**Comment by cvarjao** [comment]
closing stale issues
