### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by WhiteSeasons** [openwallet-foundation/bifold-wallet#377]
Download  the latest code and run, an error occurred

 BUNDLE  ./index.js

 LOG  i18next: languageChanged en
 LOG  i18next: initialized {"appendNamespaceToCIMode": false, "appendNamespaceToMissingKey": false, "contextSeparator": "_", "debug": true, "defaultNS": ["translation"], "fallbackLng": ["en"], "fallbackNS": false, "ignoreJSONStructure": true, "initImmediate": true, "interpolation": {"escapeValue": true, "format": [Function bound format], "formatSeparator": ",", "maxReplaces": 1000, "nestingOptionsSeparator": ",", "nestingPrefix": "$t(", "nestingSuffix": ")", "prefix": "{{", "skipOnVariables": true, "suffix": "}}", "unescapePrefix": "-"}, "joinArrays": false, "keySeparator": ".", "lng": "en", "load": "all", "missingInterpolationHandler": false, "missingKeyHandler": false, "nonExplicitSupportedLngs": false, "ns": ["translation"], "nsSeparator": ":", "overloadTranslationOptionHandler": [Function handle], "parseMissingKeyHandler": false, "partialBundledLanguages": false, "pluralSeparator": "_", "postProcess": false, "postProcessPassResolved": false, "preload": false, "resources": {"en": {"translation": [Object]}, "fr": {"translation": [Object]}}, "returnEmptyString": true, "returnNull": true, "returnObjects": false, "returnedObjectHandler": false, "saveMissing": false, "saveMissingPlurals": true, "saveMissingTo": "fallback", "simplifyPluralSuffix": true, "supportedLngs": false, "updateMissing": false}
 LOG  Running "aries-bifold" with {"rootTag":1}
 ERROR  Error: Couldn't find a navigation object. Is your component inside NavigationContainer?

This error is located at:
    in RootStack (at App.tsx:56)
    in AuthProvider (at App.tsx:48)
    in BasicMessageProvider (created by AgentProvider)
    in ProofProvider (created by AgentProvider)
    in CredentialProvider (created by AgentProvider)
    in ConnectionProvider (created by AgentProvider)
    in AgentProvider (at App.tsx:45)
    in StoreProvider (at App.tsx:44)
    in App (at app/index.js:38)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at app/index.js:37)
    in Base (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in aries-bifold(RootComponent) (at renderApplication.js:60), js engine: hermes
 ERROR  Error: Couldn't find a navigation object. Is your component inside NavigationContainer?

This error is located at:
    in RootStack (at App.tsx:56)
    in AuthProvider (at App.tsx:48)
    in BasicMessageProvider (created by AgentProvider)
    in ProofProvider (created by AgentProvider)
    in CredentialProvider (created by AgentProvider)
    in ConnectionProvider (created by AgentProvider)
    in AgentProvider (at App.tsx:45)
    in StoreProvider (at App.tsx:44)
    in App (at app/index.js:38)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at app/index.js:37)
    in Base (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in aries-bifold(RootComponent) (at renderApplication.js:60), js engine: hermes

**Comment by amanji** [comment]
Is this still an ongoing issue?

**Comment by cvarjao** [comment]
closing stale issues
