### ISSUE TITLE
Credential offer screen: Credential title and attributes not showing up

### ISSUE THREAD

**Issue by wadeking98** [openwallet-foundation/bifold-wallet#386]
Issue: After scanning a QR code to receive a credential, the user is presented with the credential details in the credential offer screen. Previously the credential attributes and title would be displayed on this screen but now it just has the default title `Credential` and no version number.

Expected behavior: The credential offer screen should display the correct credential title (in this case student card) as well as the schema version and the attributes of the student card

![image.png](https://images.zenhubusercontent.com/5fc52e1a365e55a8d5b3f428/6e6c0909-efd4-400a-a9ed-c699c44a570f)

**Comment by wadeking98** [comment]
Additional info: 
This is the credential object that gets created by the `useCredentialById(credentialId)` function in the `CredentialOffer.tsx` screen.
```json
{"_tags":{},"metadata":{},"credentials":[],"id":"91b19b8e-1edb-4659-a9b1-3106108ab63b","createdAt":"2022-07-29T17:06:34.626Z","state":"offer-received","threadId":"401f435e-4e97-4c17-90fb-9a295217c10c","protocolVersion":"v1"}
```
The credentials array is left blank which I believe is what causes the issue. I think this might be an issue with `@aries-framework/react-hooks` since the `useCredentialById` function is imported from there

**Comment by amanji** [comment]
This is more widespread than just the credential offer screens. It will also affect the display of notifications. A secondary call to `getFormatData` is required to retrieve credential info and attributes. The current solution is to patch the metadata in the credential exchange record which can be done directly in the react-hooks.
