### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by manikal** [openwallet-foundation/bifold-wallet#397]
👋 everyone,

I've followed Readme install instructions but I stuck on _npm install_ step.

npm - 8.15.0
node - 18.7.0

<img width="1675" alt="Screenshot 2022-08-06 at 11 20 33" src="https://user-images.githubusercontent.com/983154/183242998-770298a5-4b9e-4c09-9b51-a734f624c5d9.png">
<img width="697" alt="Screenshot 2022-08-06 at 11 20 46" src="https://user-images.githubusercontent.com/983154/183243003-f657102c-d532-438e-a9f7-49550ff971b9.png">

**Comment by cvarjao** [comment]
> It seems to be a problem with recent npm, can you downgrade to npm 8.5.5?
As per issue #347. We have plans to move to Yarn ( #291) and fix that, just haven't got to it yet

**Comment by manikal** [comment]
Thanks @cvarjao, it works fine with npm 8.5.5 (node 16.15.0).
