### ISSUE TITLE
chore!: Rename source directory in bifold to be less confusing

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#408]
The main source directory in the bifold wallet is named `App` which is legacy and misleading. It should be renamed to `src` to better match modern create-react-app output.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/489

**Comment by nodlesh** [comment]
@wadeking98 or @cvarjao can you close this issue? I cannot close issues in this repo. Thanks.
