### ISSUE TITLE
READM.md: Update link and adding VSC workflow

### ISSUE THREAD

**Issue by Asvoria** [openwallet-foundation/bifold-wallet#41]
I can only run using the following on visual studio  #code:

```sh
npm install --force
```

**Comment by Asvoria** [comment]
refer to pull request: #43

**Comment by TimoGlastra** [comment]
Thanks for posting this issue @Asvoria! Could you post the error you get if you don't use `--force`?

Maybe we can resolve the issue instead of adding this to the readme

**Comment by Asvoria** [comment]
Just now i tried to recreate the error without using ```--force``` while ```npm install```.  
I realised it is due to npm version 6.14.12.

After updated the npm to version 7.11.2 with the command ```nvm install v16.1.0```, 
it went through ```npm install``` without ```--force``` without error.

Below are the error occurs when using npm version 6.14.12 without ```--force```

```sh
ld: library not found for -lindy
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/indynodejs.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/asvoriakuan/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 20.4.0
gyp ERR! command "/Users/asvoriakuan/.nvm/versions/node/v12.22.1/bin/node" "/Users/asvoriakuan/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/asvoriakuan/Documents/smartloan-mobile-agent/node_modules/indy-sdk
gyp ERR! node -v v12.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> husky@4.3.8 install /Users/asvoriakuan/Documents/smartloan-mobile-agent/node_modules/husky
> node husky install

husky > Setting up git hooks
git rev-parse command failed. Got fatal: not a git repository (or any of the parent directories): .git
husky > Failed to install
```

**Comment by TimoGlastra** [comment]
Hmm only thing I can find is this issue: https://github.com/typicode/husky/issues/584

Are you running the install script from the repository root?

**Comment by TimoGlastra** [comment]
@JamesKEbert as a side question, are you fine with moving to Yarn? We're using it for AFJ and I've generally encountered less errors using Yarn for development.

Would also be nice to use yarn workspaces when/if we move to a monorepo

**Comment by TimoGlastra** [comment]
> Hmm only thing I can find is this issue: https://github.com/typicode/husky/issues/584
> 
> Are you running the install script from the repository root?

Or we could try updating husky to the newest major. We're on 4 while 6 is out

**Comment by JamesKEbert** [comment]
@TimoGlastra could this be related to our recent addition of the indy-sdk types? 

`"@types/rn-indy-sdk": "npm:@types/indy-sdk@^1.15.2",`

Since it seems to be trying to use `node-gyp`, which shouldn't be required on the RN side of things AFAIK.

**Comment by JamesKEbert** [comment]
> @JamesKEbert as a side question, are you fine with moving to Yarn? We're using it for AFJ and I've generally encountered less errors using Yarn for development.
> 
> Would also be nice to use yarn workspaces when/if we move to a monorepo

And as to the side question @TimoGlastra, I've normally preferred to utilize npm--especially since I haven't seen large benefits from using yarn, although I haven't actually done too much with yarn, so I may be mistaken there. 
So, I don't think I would be opposed since that would align us with AFJ.

**Comment by karimStekelenburg** [comment]
I'm not up to speed with this issue, just reacting to the side note here. I ran into various issues in previous projects using NPM that were all resolved by switching to Yarn. 

I'm especially in favor of using Yarn because it offers more options. For example: you can pass a `--json` option to Yarn which makes it output the STDOUT logs in JSON-Lines format. With NPM you don't have that option as far as I know. Although this is a feature we'd probably never have to use, I think it's nice to go for a package manager that offers this kind of flexibility!

**Comment by karimStekelenburg** [comment]
@Asvoria I found this StackOverlow question regarding node-gyp and `npm install --force`. You might want to try the "delete the $HOME/.node_gyp folder and run npm update" fix that is stated there. I'm not super familiar, but I have ran into some node-gyp caching issues in the past.

**Comment by JamesKEbert** [comment]
> I'm especially in favor of using Yarn because it offers more options. 

Given that I haven't really delved into `yarn` vs `npm` thoroughly I am alright switching based off your guys' endorsements of it.

**Comment by TimoGlastra** [comment]
> @Asvoria I found this StackOverlow question regarding node-gyp and `npm install --force`. You might want to try the "delete the $HOME/.node_gyp folder and run npm update" fix that is stated there. I'm not super familiar, but I have ran into some node-gyp caching issues in the past.

The node-gyp error is unrelated to this I think. AFJ has `indy-sdk` as an `optionalDependency` which means it will try to install indy-sdk, but allow it to fail. This was convenient when AFJ still needed to be manually packed, however now that it is released to NPM we should make it a dev dependency again
