### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ripulbd** [openwallet-foundation/bifold-wallet#434]
Hi,

I am facing this error and I am not sure how to resolve this. My previous installation at a different laptop was done a year ago and which worked fine. Now I am trying to install Aries Mobile Agent React-native in this new laptop and somehow it is not getting installed.

I am receiving this error as can been seen in the attached screenshot when npm install is issued.

React-native works fine and tested on a physical device following the instruction from the URL given on the Aries Mobile Agent website. 

Node version: v16.17.0, npm version: 8.15.0 and react-native version: 0.70.0. 

Any idea what is happening here! Thanks in advance.
![Screenshot from 2022-09-08 18-35-33](https://user-images.githubusercontent.com/1178467/189124701-93b470f8-e1cd-478c-9b5e-e5bbf1349576.png)

**Comment by thiagoromanos** [comment]
The github workflow for this project uses nodejs version 16.15.0. Have you tried that version?

**Comment by ripulbd** [comment]
Thanks a lot, utilising that particular version seems to solve this problem. Probably worth mentioning it in the readme file.
