### ISSUE TITLE
Add support for revocation notification

### ISSUE THREAD

**Issue by JamesKEbert** [openwallet-foundation/bifold-wallet#46]
As a developer I want to be able to identify when a credential has been revoked and be able to display a notification to the user or a warning prior to creating a presentation proof.

**Comment by jleach** [comment]
Being worked on by @ryankoch13.

**Comment by cvarjao** [comment]
@ryankoch13, any update on this?

**Comment by ryankoch13** [comment]
@cvarjao apologies for the delayed response here - I just pulled the latest from hyperledger main and I'm putting together a PR to contribute this, I'll have a link to that by EOD.

**Comment by ryankoch13** [comment]
https://github.com/hyperledger/aries-mobile-agent-react-native/pull/504

**Comment by jleach** [comment]
Done as per the PR.
