### ISSUE TITLE
Back button to splash screen should be removed

### ISSUE THREAD

**Issue by amanji** [openwallet-foundation/bifold-wallet#460]
Introduced with initialization refactor. A user can go back to the Splash screen with no way to exit without closing app.

**Comment by nodlesh** [comment]
Video attached. It isn't only the `<Splash` link that can bring one back to the initialization screen, it is also (at least on iOS) you can swipe right to go back to the initialization screen. 

https://user-images.githubusercontent.com/44370861/195704968-f9d4cdd2-e37d-404c-b91a-f7f2756051cd.mov

**Comment by jleach** [comment]
Pretty sure I fixed this. Closing as a duplicate.

**Comment by dinbtechit** [comment]
@jleach  -  was it recently fixed? We still have this issue in our fork of bifold (commit Id - 967ef)

**Comment by jleach** [comment]
@dinbtechit Ok, my mistake.

**Comment by dinbtechit** [comment]
No worries @jleach ... I was trying to fix it. For some reason,  I couldn't pop the loading screen route from the stack navigation history. The react native - stack navigator documentation is a bit convoluted. :(

**Comment by cvarjao** [comment]
Needs to be re-tested

**Comment by bryce-mcmath** [comment]
Can I be assigned to this? I'm currently testing it

**Comment by bryce-mcmath** [comment]
Back-navigation issues should now be fixed for both iOS (swipe back) and Android (hardware back button)
