### ISSUE TITLE
Add credential verification support

### ISSUE THREAD

**Issue by JamesKEbert** [openwallet-foundation/bifold-wallet#48]
As an end user and developer I would like the capability to verify credential proof presentations.

**Comment by standlove** [comment]
Hi, @JamesKEbert   

How to scan a qrcode to initiate the credential verification, is it supported by the arise javascript framework? 

Thanks.

**Comment by jleach** [comment]
Reviewed Dec 6.

@JamesKEbert Are you able to add some more colour to this issue.

**Comment by jleach** [comment]
This will be captured in the [Code With Us](https://marketplace.digital.gov.bc.ca/opportunities/code-with-us/1b4e02e9-8a2e-4970-9f12-fb2f0a827ea1) issued by the Government of BC.
