### ISSUE TITLE
Add push notifications

### ISSUE THREAD

**Issue by JamesKEbert** [openwallet-foundation/bifold-wallet#52]
As a developer I want a way to receive push notifications from a mediator to go fetch queued messages. Relevant discussion for ACA-Py: https://github.com/hyperledger/aries-cloudagent-python/issues/950

Relevant Rocketchat discussion: https://chat.hyperledger.org/channel/aries-cloudagent-python?msg=PiCe7t2SSqnFCBcMk

The mechanisms discussed could allow for an open source way (Firebase) of doing push notifications from a mediator.

**Comment by jleach** [comment]
Work in Progress on the AFJ side.

https://github.com/hyperledger/aries-framework-javascript-ext/tree/main/packages/push-notifications

**Comment by jleach** [comment]
This issue is still relevant. We want to implement Google and Apple push notifications.
