### ISSUE TITLE
Demo, error and aca-py

### ISSUE THREAD

**Issue by dukmarques** [openwallet-foundation/bifold-wallet#53]
Hello, first I would like to know if there is any document / video of the project execution, demonstrating how to execute, establish a connection and receive credentials using the test networks indicated in the readme (Indicio TestNet / Sovrin StagingNet)?

Second, I am trying to execute the project, however I am having problems in responding to the AFJ mediator, as in the image below.
![error](https://user-images.githubusercontent.com/33849830/118908635-28275a80-b8f8-11eb-805a-174852f4c331.png)

The ngrok address shown is correct in relation to that displayed by the AFJ when I run the mediator.

Thirdly, is it possible to carry out the project with aca-py as the issuing agent? before the error pointed out above, I couldn't connect to aca-py!

Finally, congratulations on the project!

**Comment by JamesKEbert** [comment]
Hello @dukmarques! I'm glad you've been able to try the project out!

1. As of right now the best documentation is on the project readme, but I'd be interested in creating a bit more of a walkthrough document to help on our documentation efforts. I'd also be happy to help answer questions/clarifying things here or on Rocketchat! We could also do a demo/walkthrough on the next Aries Bifold User Group call.

2. Since AFJ has had a bunch of updates recently, I am wondering if AFJ @ main for running a mediator is incompatible with where the Bifold project is right now. I've asked @TheTreek to investigate and see if he can replicate your issue. If my thoughts are correct then we just need to update our mediation instructions to tie it to the appropriate version. 

3. And yes! This will work with ACA-Py as the issuer. I've primarily tested via the Aries Toolbox, which uses ACA-Py for its functionality. Given the above error it's more likely an issue with mediation vs ACA-Py.

Thank you! 😄

**Comment by dukmarques** [comment]
Hi @JamesKEbert , thanks for the replies!

1 - If possible, I ask that when performing the demonstration in the group call, that I can make it available afterwards, I cannot confirm my presence due to my schedule and would help me a lot if I had access to the content.

2- Okay, thank you very much, I'm waiting. A note, I believe that the mobile agent, in my execution, is able to communicate with the mediator and after a few messages he presents this error.

3 - Interesting, can you establish a connection and after issuing credentials normally? Is there a demo of the Aries Toolbox?

Thank you very much for your attention and answers!

**Comment by JamesKEbert** [comment]
1. And we definitely can make it available afterwards--we record every call actually to allow people to watch if they're unable to make it or anything. The recordings just get posted at the bottom of the meeting notes of every week.

2. I can confirm that my suspicion is unfortunately not the issue. Is there something in particular that triggers this error, or just after a couple of messages with the mediator it occurs? I would love to be able to recreate the issue. Also, we can  probably add additional logging around this to help give additional context.

3. We have done that as well. I don't know if there's a demo easily accessible on the Aries Toolbox actually. @dbluhm is the expert on the Toolbox, if you have additional insight. 
AFAIK, you should be able to follow the documentation to set up ACA-Py with the Toolbox plugin here: https://github.com/Indicio-tech/aries-acapy-plugin-toolbox
And then the corresponding Toolbox UI:
https://github.com/hyperledger/aries-toolbox

**Comment by dukmarques** [comment]
Hello @JamesKEbert, sorry for the delay in answering you.

I have followed the steps present in the readme and the commands in the docs folder to upload the mediator.

After them, I realize that the mediator and the agent mobile make the connection, exchange some messages and stop, below I leave some logs that I believe can help.

I added to the gist due to the size, and added only the initial parts, where the connection is made between them, after that they just exchange messages until they stop.
Aries Mobile React Native logs: https://gist.github.com/dukmarques/67347d4f9c393da7fb5128ce96fca3f5

Mediator logs: https://gist.github.com/dukmarques/9c0839355b60e2b7d5773753250c8067

I realized this time that after presenting the error in the image that I attached above, they communicated again and then presented the error again and the communication ceased, when clicking on DISMISS, the error is presented right away.

I did not identify any error logs, either in the agent or in the mediator.

**Comment by dukmarques** [comment]
About him resuming communication with the mediator, I believe he has tried the connection again, when the cell phone locks the screen due to inactivity (with the agent app open), he ceases communications, by unblocking it, he returns to communication with the mediator for a period of time (just over 1 minute) and stops.
So I believe that in this process, when unlocking the screen, he starts communication with the mediator again, but shortly thereafter the agent is no longer able to communicate with the mediator and presents the image error.

**Comment by TimoGlastra** [comment]
We've had a discussion about this on the Aries Bifold WG call. ngrok has a limit on the polling interval and it may be the case that you're reaching the limit here. 

We have a publicly hosted instance of an AFJ mediator at http://mediator.animo.id. Could you try to run with this url as `mediatorUrl` and see if the problem persists?

**Comment by WhiteSeasons** [comment]
> We've had a discussion about this on the Aries Bifold WG call. ngrok has a limit on the polling interval and it may be the case that you're reaching the limit here.
> 
> We have a publicly hosted instance of an AFJ mediator at http://mediator.animo.id. Could you try to run with this url as `mediatorUrl` and see if the problem persists?


I have run with this url， problem as picture show， fromt the latest branch version ：
![03F19599-21B8-497e-944B-9177E1F3F175](https://user-images.githubusercontent.com/87514220/128155464-969bac64-fbee-4055-a33c-b1e511e38360.png)

so why and how to solve ？

**Comment by TimoGlastra** [comment]
This is a bit unfortunate, but AFJ recently had a major overhaul to how mediation works. The public mediator hosted at mediator.animo.id has been updated since, but this repo hasn't. 

So I think the solution for now will be to check out AFJ at the version before we made the changes to how mediation works: https://github.com/hyperledger/aries-framework-javascript/releases/tag/0.0.60-unstable.0

**Comment by WhiteSeasons** [comment]
> This is a bit unfortunate, but AFJ recently had a major overhaul to how mediation works. The public mediator hosted at mediator.animo.id has been updated since, but this repo hasn't.
> 
> So I think the solution for now will be to check out AFJ at the version before we made the changes to how mediation works: https://github.com/hyperledger/aries-framework-javascript/releases/tag/0.0.60-unstable.0

Thanks for your reply.  i want to  run the Aries Mobile and connect to the mediation,  which vesion is compatible， just for demo show。

**Comment by jleach** [comment]
As per todays Bifold WG call we're closing stale our otherwise dormant issues. Please re-open if its still relevant.
