### ISSUE TITLE
Message in undeliverable to connection error

### ISSUE THREAD

**Issue by Durai46** [openwallet-foundation/bifold-wallet#534]
We are seeing a mediator connection error in the APP screen. We have configured our own Mediator URL & Genesis URL in .env file and both are running on local machine. Could you please help?

**Failure message : Message is undeliverable to connection d723ed00-9616-4869-8Od8-57527ee1b129 (Mediator)**

#### .env file:

MEDIATOR_URL=[http://191.161.1.4:3006?c_i=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL2Nvbm5lY3Rpb25zLzEuMC9pbnZpdGF0aW9uIiwgIkBpZCI6ICJjMTI2MTIzMi1hYTY4LTQ2ODYtODAyZS0wNDMxMjU3NzZjMmMiLCAic2VydmljZUVuZHBvaW50IjogImh0dHA6Ly8xOTIuMTY4LjEuNDozMDA2IiwgImxhYmVsIjogIk1lZGlhdG9yIiwgInJlY2lwaWVudEtleXMiOiBbIkNMMUFLRk1GUFR2d2h0V0U1ODJ3dzRxVEZpQXV6VzVuNEFKUTJNNDhOODhDIl19](http://191.161.1.4:3006/?c_i=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL2Nvbm5lY3Rpb25zLzEuMC9pbnZpdGF0aW9uIiwgIkBpZCI6ICJjMTI2MTIzMi1hYTY4LTQ2ODYtODAyZS0wNDMxMjU3NzZjMmMiLCAic2VydmljZUVuZHBvaW50IjogImh0dHA6Ly8xOTIuMTY4LjEuNDozMDA2IiwgImxhYmVsIjogIk1lZGlhdG9yIiwgInJlY2lwaWVudEtleXMiOiBbIkNMMUFLRk1GUFR2d2h0V0U1ODJ3dzRxVEZpQXV6VzVuNEFKUTJNNDhOODhDIl19)

GENESIS_URL=http://host.docker.internal:9000/genesis

**Comment by trieulethe** [comment]
Is this a fix @Durai46? I got the same error but I don't know how to fix that.

**Comment by cvarjao** [comment]
closing stale issues
