### ISSUE TITLE
Connection screen going nowhere

### ISSUE THREAD

**Issue by thiagoromanos** [openwallet-foundation/bifold-wallet#552]
After scanning a qrcode of an invitation, made from a old connections or a oob invitation whithout attachment, the connection screen stays there and doesn't go back home after the connection is completed. 
I'm using a aca-py agent to make the invitation. I checked that agent and the connection state is "completed" there if I use the connections protocol. If I use didexchange as the protocol for and oob invitation, the status is "invitation" (means the connection wasn't completed??).

**Comment by HiraSiddiqui** [comment]
Has somebody looked into it yet? I am experiencing the same problem.

**Comment by tgallant-amex** [comment]
Looking at the Connection.tsx file in the core, the only way to clear this modal is via notifications update, but there are only 2 types of notifications that can happen (credentialRecord and proofRecord). We need to be able to view the connection status "complete" to clear the invitation but not seeing how to access that information.
