### ISSUE TITLE
Credential list not updating when credential revocation notification received

### ISSUE THREAD

**Issue by amanji** [openwallet-foundation/bifold-wallet#563]
If on credential list view and revocation notification received, the list of credentials are not updated to reflect the revoked credentials. Even after navigating away from the view and back does not reflect the revocation. Only after closing and reopening the wallet does the list display the revocation status.

**Comment by amanji** [comment]
[Credential list not updating when revocation received.webm](https://user-images.githubusercontent.com/5605464/207136114-8f28b3ec-46e5-4ae5-84d1-ef9168ad1776.webm)

**Comment by wadeking98** [comment]
I'll take this one but github isn't allowing me to assign myself
