### ISSUE TITLE
Proof request not updating to reflect revoked credentials

### ISSUE THREAD

**Issue by amanji** [openwallet-foundation/bifold-wallet#564]
Normally when a proof request is initiated the wallet will determine whether any of the requested attributes are from revoked credentials. If during that time a credential offer is made with attributes that are not revoked, the proof request will update to reflect the non-revoked attributes. This does not happen in the reverse scenario. If a credential is initially not revoked but is revoked after a proof request is received, the proof request will not update to reflect those now revoked attributes

**Comment by amanji** [comment]
Normally when a proof request is initiated the wallet will determine whether any of the requested attributes are from revoked credentials. If during that time a credential offer is made with attributes that are not revoked, the proof request will update to reflect the non-revoked attributes. This does not happen in the reverse scenario. If a credential is initially not revoked but is revoked after a proof request is received, the proof request will not update to reflect those now revoked attributes

**Comment by amanji** [comment]
[Proof request updates when new credential recieved.webm](https://user-images.githubusercontent.com/5605464/207137503-e70d2374-ad0b-4541-8a5c-4ce5185f9000.webm)

Here a proof request correctly updates when a new credential is obtained

**Comment by amanji** [comment]
[Proof request not updated when credential revoked.webm](https://user-images.githubusercontent.com/5605464/207137718-836d6b53-3088-4f56-95e7-b7bec985163f.webm)

Here a proof request does not update when an attribute is pulled from a revoked-in-flight credential

**Comment by wadeking98** [comment]
@amanji I'll tackle this issue but I don't have the ability to assign myself for some reason

**Comment by wadeking98** [comment]
Akiff and I agree that this seems to be an issue with AFJ. The issue is that when an agent requests credentials to satisfy a given proof request, it only scans the revocation registry up to the date that the proof request was created. Any revocation notifications created after the proof request will be missed:
![image.png](https://images.zenhubusercontent.com/5fc52e1a365e55a8d5b3f428/5b957f6e-81ae-430b-91aa-c4b401703b30)

**Comment by cvarjao** [comment]
@wadeking98 has indicated that this is blocked by fixes to AFJ

**Comment by amanji** [comment]
I've added myself to validate whether this is actually a bug

**Comment by cvarjao** [comment]
This work as expected. The proof request was received with a proof of non revocation in the past and even if the credential has now been revoked, it was still non-revoked when it was first requested.
