### ISSUE TITLE
Settings section "What are contacts?" is not working

### ISSUE THREAD

**Issue by thiagoromanos** [openwallet-foundation/bifold-wallet#572]
In the Settings screen, if I click to go to "What are contacts?" section, nothing happens.

**Comment by knguyenBC** [comment]
We'll be adding content that describes in plain language what Contacts are in the near future.

**Comment by thiagoromanos** [comment]
> We'll be adding content that describes in plain language what Contacts are in the near future.

In that case, I think it would be better to hide that section and show it again when the section is ok to be shown, because the way it is now looks like a bug.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/599
