### ISSUE TITLE
Unable to share proof request with Animo Demo

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/bifold-wallet#577]
When using the bifold wallet with the [Animo Demo](https://demo.animo.id), it will consistently fail on the step of sharing a proof request. At first I thought it may be a ledger issue, but receiving the credential has no issues.

This happens in both the BC Wallet and Indicio Holdr+ Wallet. 

See attached screenshots. The demo is using the BCovrin Test Network

![IMG_8230](https://user-images.githubusercontent.com/23165168/209051790-fe570f05-4302-4aac-8d96-0791082ebb9c.PNG)
![IMG_8228](https://user-images.githubusercontent.com/23165168/209051799-02e2bbda-8796-4d6c-988f-a8fef604fb0b.PNG)

**Comment by TimoGlastra** [comment]
cc @amanji @JamesKEbert

**Comment by JamesKEbert** [comment]
Happy New Year!
This is interesting--I'll ask my team to look into this. Do you know if the Animo demo is using connectionless proof requests or standard requests?

**Comment by TimoGlastra** [comment]
I figured out the issue...

Our did was registered on multiple ledgers. The bifold wallets would resolve the did from the other ledger and then couldn't find the schema on it, because it was only registered on the other ledger. It's fixed now by updating the did used in the animo demo, and making sure it's only registered on the one ledger

**Comment by TimoGlastra** [comment]
Actually -- you figured out the issue 😄

**Comment by JamesKEbert** [comment]
Ahhh I was thinking this was a followup issue. Wonderful 💥
