### ISSUE TITLE
Add support for the shared component libraries in Aries Bifold

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/bifold-wallet#581]
Should be straightforward once integrated into AFJ. Tricky part will be in how to switch between Indy SDK and Shared components in Bifold, and making sure we don't add all binaries to the final build. 

Maybe separate branches? Or we can maybe add a metro / react native config that will explicitly remove the unused dependencies

**Comment by cvarjao** [comment]
closing stale issues
