### ISSUE TITLE
Credential Render Error (OCA Bundle) 

### ISSUE THREAD

**Issue by Wahed08** [openwallet-foundation/bifold-wallet#583]
Hi, 
I am trying to add a backup and restore option in the Wallet.  When I try to restore from backed up credentials I am facing some errors.

I am trying to insert credential as JSON object into the existing credential array. I want to render my credentials also my restored one  into **ListCredentials.tsx** component which is calling **CredentialCard** component for rendering in the mobile UI.

I am wanting to update **credentials** array in the **ListCredential** component. Then when I am trying to call **OCABundle.getCredentialPresentationFields()** method it gives us following error. 

**a restored JSON Object**:
`{
        "_tags": {
            "credentialIds": [
                "a3b9427d.."
            ],
            "threadId": "5d9...",
            "connectionId": "49...",
            "state": "done"
        },
        "metadata": {
            "_internal/indyRequest": {
                "master_secret_blinding_data": {
                    "v_prime": "1379325853110746942345668895835114361603644361418245429527742139915313807970276743939003969249826285086162039922666281825501240978160383322471999882224223636799143678547582632368562690666839570389650200484803078201819653192112695225582065877198148977390525705734288593072953662291253639212190422453091960150602885773993345999206524506795948470617990347805577383953099963810085724504508790210488414788688019918971113020805457989619950242439708896657595202851548725596240037546632406913779433567749873848670751327471808380908010168017301343585296187042050793601274297218485283245963910648143822275137160203523412263666641440331455231399110032",
                    "vr_prime": null
                },
                "nonce": "479575988319662591578697",
                "master_secret_name": "walletId"
            },
            "_internal/indyCredential": {
                "credentialDefinitionId": "36JBUCTsys5CxwUfXgWfRw:3:CL:156343:faber.agent.degree_schema",
                "schemaId": "36JBUCTsys5CxwUfXgWfRw:2:degree schema:76.99.28"
            }
        },
        "credentials": [
            {
                "credentialRecordType": "indy",
                "credentialRecordId": "a3b9427d.."
            }
        ],
        "id": "007a1826..",
        "createdAt": "2022-10-29T12:22:06.748Z",
        "state": "done",
        "connectionId": "49...",
        "threadId": "5d9...",
        "protocolVersion": "v1",
        "credentialAttributes": [
            {
                "mime-type": "text/plain",
                "name": "birthdate_dateint",
                "value": "34895495454"
            },
            {
                "mime-type": "text/plain",
                "name": "name",
                "value": "Will Smith"
            },
            {
                "mime-type": "text/plain",
                "name": "timestamp",
                "value": "1667046093016"
            },
            {
                "mime-type": "text/plain",
                "name": "degree",
                "value": "Math"
            },
            {
                "mime-type": "text/plain",
                "name": "date",
                "value": "1667046093016"
            }
        ]
    },`

**in Metro error**
![323752460_725221785532309_9122066974172566904_n](https://user-images.githubusercontent.com/43209260/211189101-f8120088-f58b-4f9f-824e-9826ce42ef99.png)

**in Mobile error**
![321303192_700942178208003_733301269240045959_n](https://user-images.githubusercontent.com/43209260/211189143-c9deec9b-c65a-432b-a60b-ed85ab71c14c.jpg)

![321964986_1453560408505869_3011923011505926968_n](https://user-images.githubusercontent.com/43209260/211189144-252b107b-5c72-4241-852f-2500bd89d27e.jpg)
)

**Is this exact way to inserting into credential array and then render it in the UI?**
**If not then how can I do that?**

Thanks in advance.

**Comment by cvarjao** [comment]
as noted in AFJ call, please use the import/export methods available in AFJ. It might be missing some metadata attributes
