### ISSUE TITLE
Error: Connection record is not ready to be used

### ISSUE THREAD

**Issue by MosCD3** [openwallet-foundation/bifold-wallet#59]
I am trying to get Bifold to accept an invitation sent by a DTS issuer running on my local machine
I cannot get pass this error  after scanning the barcode of the credential invitation
[javascript] Possible Unhandled Promise Rejection (id: 0):
Error: Connection record is not ready to be used. Expected responded or complete, found invalid state requested
Error: Connection record is not ready to be used. Expected responded or complete, found invalid state requested

Steps:
- Run bifold
- Connected to mediator success
- Run dts local issuer
https://github.com/bcgov/dts-vc-issuer-service
- Generate vaccination credential 
- Scan credential with bifold
- The wallet switches to 'connecting'
- Nothing happens from there

Just to make things easier
this is the last message received from issuer right before the exception happens

{
  "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/offer-credential",
  "@id": "cfb0d143-0705-41ec-8d1d-74ae3945f934",
  "~thread": {},
  "offers~attach": [
    {
      "@id": "libindy-cred-offer-0",
      "mime-type": "application/json",
      "data": {
        "base64": "[Base 64 data]"
      }
    }
  ],
  "credential_preview": {
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/credential-preview",
    "attributes": [
      {
        "name": "name",
        "value": "Vaccination Certificate"
      },
      {
        "name": "description",
        "value": "Vaccination Certificate"
      },
      {
        "name": "expirationDate",
        "value": "2022-06-30T04:46:57.6417668+00:00"
      },
      {
        "name": "credential_type",
        "value": "VaccinationEvent"
      },
      {
        "name": "countryOfVaccination",
        "value": "CA"
      },
      {
        "name": "recipient_type",
        "value": "VaccineRecipient"
      },
      {
        "name": "recipient_fullName",
        "value": "SCHITT, Roland Ethan"
      },
      {
        "name": "recipient_birthDate",
        "value": "01/14/1952"
      },
      {
        "name": "vaccine_type",
        "value": "Vaccine"
      },
      {
        "name": "vaccine_disease",
        "value": "Influenza"
      },
      {
        "name": "vaccine_medicinalProductName",
        "value": "Fluzone High-Dose"
      },
      {
        "name": "vaccine_marketingAuthorizationHolder",
        "value": "SANOFI PASTEUR LIMITED"
      },
      {
        "name": "vaccine_dateOfVaccination",
        "value": "09/22/2020"
      }
    ]
  },
  "comment": "create automated credential exchange"
}

I attached the log from both the issuer and the bifold terminal

[agent_invitee.txt](https://github.com/hyperledger/aries-mobile-agent-react-native/files/6738178/agent_invitee.txt)
[issuer_log.txt](https://github.com/hyperledger/aries-mobile-agent-react-native/files/6738179/issuer_log.txt)

I also can't seem to find where I should add breakpoints in the code to dive deep in the process
It seems like the last event I can get to is 

components>GRCodeScanner>index.js

`const connectionRecord = await agentContext.agent.connections.receiveInvitation(decodedInvitation, {
      autoAcceptConnection: true,
    })

//that's the last point I could reach
console.log('New Connection Record', connectionRecord)`

I don't seem to be able to reach with the debugger breakpoints to this line though

Workflows>index.js
`const handleCredentialStateChange = async (event) => {
    console.info(`Credentials State Change, new state: "${event.credentialRecord.state}"`, event)
..... 
}`

Which I believe runs if there was to be a successful connection attempt

Any more thoughts?

**Comment by TimoGlastra** [comment]
Fixed by hyperledger/aries-framework-javascript#339
