### ISSUE TITLE
Create a standalone playground tool to for issuers that implements the OCA Style Guide

### ISSUE THREAD

**Issue by swcurran** [openwallet-foundation/bifold-wallet#594]
As the Aries community discusses the OCA Style Guide ([PR](https://github.com/hyperledger/aries-rfcs/pull/755), [PR branch Style Guide document](https://github.com/swcurran/aries-rfcs/blob/oca4aries/features/0756-oca-for-aries-style-guide/README.md)), it would be helpful to have a tool/playground that lets community members experiment with the (currently proposed) OCA style guide.  The tool would be a standalone JS file that allows the user to do the following in a browser:

- Load an OCA Bundle JSON
- Enter some additional data:
   - If primary attribute is present -- a value of the primary attribute
   - If secondary attribute is present -- a value of the secondary attribute
   - If the expiry_attribute is set -- a checkbox for "Expired"
   - A checkbox for "Revoked"
- Calculate the values that make up the layout elements (same code as in Aries Bifold)
- Display the card and credential layouts (similar code as in Aries Bifold -- but web only)
- Allow the user to change languages for the languages in the Meta layer.

The initial use of the tool is to let Aries community experiment with layouts and propose adjustments.
Longer term, the tool will be used by Issuers to make sure that their bundles meet their needs during development.

Nice to have -- ability to load multiple OCA Bundles, with additional data entry for each, and show the credentials together in the card view.

**Comment by swcurran** [comment]
@amanji — let me know if you want to discuss.

**Comment by cvarjao** [comment]
closing stale issues
