### ISSUE TITLE
Location of credentials

### ISSUE THREAD

**Issue by ananthu-sk** [openwallet-foundation/bifold-wallet#597]
Hi Guys, thank you for the project.

I am new to aries. Where are the credentials stored in the android device. I already checked database and shared_preference directory but haven't found the credentials.

**Comment by cvarjao** [comment]
Credentials are stored locally in an encrypted sqlite database  which is managed by indy-sdk. The app is marked as to [not allow backup](https://github.com/hyperledger/aries-mobile-agent-react-native/blob/a073a647a925a2f97bd18e94e3264a5c2136e90e/app/android/app/src/main/AndroidManifest.xml#L15) so you might not be able to browse the files.
If you want to browse the files, you may want to change that flag for your local/dev environment

**Comment by ananthu-sk** [comment]
Thanks @cvarjao,

![image](https://user-images.githubusercontent.com/25929911/227172166-7e908a10-a037-4762-b9cb-87af27188366.png)

I changed the allowBackup flag. And made backup but couldn't find the encrypted credential rows (below screenshot) in `apps/com.ariesbifold/ef/.indy_client/wallet/walletId/sqlite.db` , i have 3 credentials in my wallet. Any idea why this is.

![image](https://user-images.githubusercontent.com/25929911/227173398-586a9745-4124-4b54-a686-5355d6c913f0.png)
