### ISSUE TITLE
Unable to scan QR code after upgrading from AFJ 0.2.x to 0.3.3

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#625]
After the update to AFJ 0.3.3 existing wallets produce an error when scanning a QR code.

How to reproduce:

1. Install an older version of the wallet with AFJ 0.2.x ;
2. go through the [BC Showcase](https://digital.gov.bc.ca/digital-trust/showcase/)
3. Upgrade to a wallet with 0.3.3
4. go through the [BC Showcase](https://digital.gov.bc.ca/digital-trust/showcase/)

The app will fail to scan QR codes on step 4 above.

**Comment by amanji** [comment]
Testing with ACA-Py `1.0.0-rc1` looks to have resolved some issues. Will confirm on the `test` and `prod` environments before moving this for review.

**Comment by jleach** [comment]
The following tests completed Ok. Unable to preproduce this issue with ACA-py mediator 0.8.0.

1. Install wallet v1.0.6
2. Ran through showcase demo, prod mediator (0.7.x)
3. Install wallet v1.0.7 (latest), ran walled and confirmed upgrade from AFJ 0.2.x to 0.3.3.
4. Ran though show case demo, test mediator (0.8.0)

No errors or problems.


![Screenshot 2023-02-17 at 12.15.57 PM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/dc16eafa-c703-46de-90fe-9955eecd238b)

![Screenshot 2023-02-17 at 12.16.17 PM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/6fead90b-88be-4568-b444-61200081ca16)

**Comment by bryce-mcmath** [comment]
I also completed the above test, it's working for me as well

**Comment by jleach** [comment]
Closing. Fix is to update to a later version of ACA-py mediator. In our case 0.8.x.
