### ISSUE TITLE
Replace faux state management with event based system

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#630]
We're using the redux/state management as a sudo event system. It would be much better to actually use a proper pub/sub mechanism, preferably one native to node/Hermes. There is the standard nodejs event system which I believe is supported by Hermes and also one [built into RN](https://github.com/facebook/react-native/blob/main/Libraries/vendor/emitter/EventEmitter.js) (a little thin on documentation).

This PR needs to include:

- [ ] Integrating / wrapping / whatever is needed to use. one of the two event systems noted in the description above;
- [ ]  Replace existing usage of the state management system with an event system. Known locations include:
- - [ ]  Pin-changed in Settings (undo state change from [562](https://github.com/hyperledger/aries-mobile-agent-react-native/pull/562))
- - [ ]  addCredentialPressed in credential list screen (BC Wallet only)
- - [ ]  ErrorDispatchAction

**Comment by wadeking98** [comment]
resolved by: https://github.com/bcgov/bc-wallet-mobile/pull/907 https://github.com/hyperledger/aries-mobile-agent-react-native/pull/629
