### ISSUE TITLE
SyntaxError: JSON Parse error: Unexpected token: <

### ISSUE THREAD

**Issue by WhiteSeasons** [openwallet-foundation/bifold-wallet#66]
When launch the latest version， an error will be reported when the APP is running ： 

![02A50DE4-9FC9-4558-8735-6CEBB3C2945E](https://user-images.githubusercontent.com/87514220/127269581-c5fd091a-adfe-44f3-9151-5d8e0ab10f65.png)

so what's the problem and how to solve ，thanks~

**Comment by WhiteSeasons** [comment]
Second question，Is there any related demo that supports credential transfer， and  compatible with this version of the app ?

**Comment by mateus-n00b** [comment]
Hey, this is caused when trying to recover mediator verkey. I didnt find any solution till now. Seems to be a bug in the suggested mediator. 

Regards

**Comment by WhiteSeasons** [comment]
> Hey, this is caused when trying to recover mediator verkey. I didnt find any solution till now. Seems to be a bug in the suggested mediator.
> 
> Regards

Change the mediator，this problem is also exist，detailed in the link：

https://github.com/hyperledger/aries-mobile-agent-react-native/issues/53#issuecomment-892500638
