### ISSUE TITLE
Support for Invitation/Connection Label as default issuer name (OCA)

### ISSUE THREAD

**Issue by cvarjao** [openwallet-foundation/bifold-wallet#660]
![Screenshot](https://images.zenhubusercontent.com/5c75a872bb88ef3edd6c33ec/575d5e73-d09d-4b5b-b1da-3bfde6d9f0c7)

https://github.com/hyperledger/aries-mobile-agent-react-native/blob/881f5b93b37d2f098a4f1bca8284c4ca1f84ecdf/core/App/types/oca.ts#L223

Issue name lookup priority:
- OCA issue name
- Connection label/alias
- Connection ID
- "unknown"

**Comment by bryce-mcmath** [comment]
What it should look like after the bifold submodule has been updated
![Screenshot 2023-04-04 at 3.46.46 PM.png](https://images.zenhubusercontent.com/63bc52dfbcde5d544793e7d3/88b0544d-abeb-405c-99cc-de951e7e674c)

**Comment by nodlesh** [comment]
@bryce-mcmath I can't move this to done. Can you move it for me? Thanks.
