### ISSUE TITLE
TestIDs are no longer found on attributes and values on the proof request screen

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/bifold-wallet#664]
### Steps to Reproduce

``` gherkin
Given I have a credential
And I have a proof request
When When I review the proof request 
Then the attributes and values no longer have TestIDs
```

![Screenshot 2023-03-16 at 6.24.42 PM.png](https://images.zenhubusercontent.com/5e3864b3b64bc2429a017886/341872e1-ab43-4608-bd69-4473d5ca03b3)

### Expected Result
All Attributes and Values would have the same TestIDs of  `com.ariesbifold:id/AttributeName` and `com.ariesbifold:id/AttributeValue`. 
The existing test code does a find_multiple_by_id() to return a collection of all attributes and all values. 

 
### Environment
BC Wallet build 750
iOS and Android

### Workaround
None

### Severity
Medium

### Priority
High

### Test Impact
T001-Proof

**Comment by nodlesh** [comment]
This still remains an issue in build 791 on both iOS and Android.

**Comment by nodlesh** [comment]
@bryce-mcmath Can you move this back to Sprint Backlog? I don't have permissions in this repo.

**Comment by bryce-mcmath** [comment]
Done. For other devs looking into this, two points:
- Nested `Text` components won't propagate child testIDs
- Child components of `Touchable*` tags don't always propagate testIDs unless they have `accessible={false}`

**Comment by jleach** [comment]
@nodlesh I added the testIDs and checked that I can see them in Appium Inspector. Screen shots are in the PR. Let's see if you see them also. If not I'll try a harder :)
