### ISSUE TITLE
Unable to parse response message!

### ISSUE THREAD

**Issue by dolly1997** [openwallet-foundation/bifold-wallet#671]
we have configured ACA-py mediator with aries bifold react native mobile app .We are able to establish the connection between mediator and Bifold mobile app. while communicating with mediator we encounter the error which says "Unable to parse response message".

I have attached the error snap for the reference.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/40203065/226560146-ae1a0589-54cb-46e2-a92b-d62cf88cc389.png)
@jleach could you please look into this?

**Comment by cvarjao** [comment]
@dolly1997 , based on the responseMessage (`405 method not allowed`), it seems like something is not configured properly. My guess is that it is something to do with the "serviceEndpoint"

**Comment by dolly1997** [comment]
@cvarjao Thanks for your Response.

We have figured out the issue it was the websocket endpoint configuration which was not set properly.
Issue has been resolved.
