### ISSUE TITLE
Sender Key Undefined in Mediator logs

### ISSUE THREAD

**Issue by PenguinTaro** [openwallet-foundation/bifold-wallet#677]
Hi, 
While running the Bifold Mob App using afj-mediator, I got this information in my mediator logs that says my Sender key is undefined for routing things. But for other api calls I am able get the sender key. So my doubt is that will we get the sender key for the routing call, if so how can I rectify this issue?
I am attaching the snap for reference.
<img width="802" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/99000637/227134646-10be9388-09de-4fe9-81ea-b4827fcdfb62.png">
@swcurran @reflectivedevelopment @jleach @cvarjao  Please have a look and give me some information for the following.
Thank you for the help.

**Comment by cvarjao** [comment]
question about AFJ itself should be directed to the `aries-javascript` channel in discord on the AFJ repository

**Comment by PenguinTaro** [comment]
I didn't knew it error from mediator or the bifold aap so I post it here. I will do one in there .Thank you
