### ISSUE TITLE
Connection Successful but Connection Screen going nowhere

### ISSUE THREAD

**Issue by HiraSiddiqui** [openwallet-foundation/bifold-wallet#681]
On creating a connection, the connection screen keeps on loading and never returns to the homepage.

However, the connection is successful in the backend and if you manually press the back button and go to contacts, the connection is created and messages are also being sent. 

I think the Mobile Agent is waiting on a certain status or field that doesn't update and the loader never exits. 
![338455151_6008676865888756_1374387580291635409_n](https://user-images.githubusercontent.com/18054461/227971933-c17af655-8f65-41fb-9965-0ff6b397247e.jpg)

**Comment by cvarjao** [comment]
@HiraSiddiqui, that is the expected behaviour. The connection screen currently waits for a "Credential Offer" or "Proof Request".

**Comment by thiagoromanos** [comment]
I just opened a PR fixing this (#685)... so, when the timer is reached and the connection is active, it goes back to home.

**Comment by thiagoromanos** [comment]
BTW, this issue was already adressed before (https://github.com/hyperledger/aries-mobile-agent-react-native/issues/552)

**Comment by bryce-mcmath** [comment]
has been fixed (configurable behavior now)
