### ISSUE TITLE
is there a Agent Middleware to handle incoming messages like in the .Net IAgentMiddleware ?

### ISSUE THREAD

**Issue by bilal12367** [openwallet-foundation/bifold-wallet#683]
@TimoGlastra @amanji @jleach @JamesKEbert  I need Agent Middleware interface similar to IAgentMiddleware present in .Net . So I can apply custom logic on all incoming messages from middleware.

**Comment by jleach** [comment]
@bilal12367 Bifold uses [AFJ](https://github.com/hyperledger/aries-framework-javascript) for all communications. Better to create the issue there as we cannot address this via Bifold.
