### ISSUE TITLE
Hide Revealed Attributes while Proof Presentation

### ISSUE THREAD

**Issue by PenguinTaro** [openwallet-foundation/bifold-wallet#689]
Hi @reflectivedevelopment @JamesKEbert 
I have a question regarding the revealed flag present in requested attributes while showing the proof presentation in Bifold app. 
Do we have any flag where we can set it as False so that we can hide the data while presenting the proof to verifier?
I am asking about the marked one.
![Screenshot (146)](https://user-images.githubusercontent.com/99000637/229096897-b52fa621-9cc8-4381-ba78-fefa33483f86.png)

**Comment by cvarjao** [comment]
Unless the verifier is using predicates or ZNP they will see the requested data.

**Comment by PenguinTaro** [comment]
Thank you for the update about that point but  I want to know that is there any flag defined that can set it to false when we use predicates ?

**Comment by jleach** [comment]
@PenguinTaro Predicates don't share data. You may see it on your proof approval screen in a wallet but the verifier won't see the data - they'll just get an answer to the question. For example, age > 18 = true. In this case they'll have no idea about your age or DOB.

**Comment by PenguinTaro** [comment]
Okay got it. Thank you for clarification.

**Comment by jleach** [comment]
Closing. Re-open if you have more questions.

**Comment by PenguinTaro** [comment]
@jleach Hi again, Actually in our use case we want to set the revealed flag to false so that verifier doesn't receive the details of my attributes. Can you guide me regarding this, like how this can be achieved? 
Thank you.

**Comment by jleach** [comment]
@PenguinTaro That would be an AFJ question. Best to ask them in Discord.

**Comment by PenguinTaro** [comment]
Thank you @jleach  , and will do it
