### ISSUE TITLE
Provisioning error

### ISSUE THREAD

**Issue by phearaeun** [openwallet-foundation/bifold-wallet#69]
I received the following error while provisioning.

```
DEBUG  DEBUG: Provision record with id 'UNIQUE_PROVISIONING_ID' not found. {
  "indyError": "WalletItemNotFound"
}
 INFO  INFO: No provision record found.
```

**Comment by WhiteSeasons** [comment]
start met the same problem，  what‘s the problem  and how  to solve

**Comment by chheunpheara** [comment]
This is not resolved but I am sure we can ignore it for now till the latest update arrives. If you want to make it works, on AFJ, you should use this release `0.0.60-unstable.0` to start the mediator.
