### ISSUE TITLE
Run error on MacOs

### ISSUE THREAD

**Issue by Livbunthorn** [openwallet-foundation/bifold-wallet#699]
When I try to run aries mobile agent react native on MacOs, I got this error. What cause of this problem and how to fix it?
![Screenshot 2023-04-05 at 9 32 39 AM](https://user-images.githubusercontent.com/53400549/230108201-10309eb7-5ba9-49a3-9650-3dba844ed7b7.png)

**Comment by jleach** [comment]
@Livbunthorn Run `yarn install`, its not an `npm` project. General rule of thumb is when you see a `yarn.lock` file its a yarn project.
