### ISSUE TITLE
Demo website to use this app for credentials storing and proof verifications?

### ISSUE THREAD

**Issue by xtrycatchx** [openwallet-foundation/bifold-wallet#70]
I managed to run build and run the app in IOS with the following:
-  genesis using : https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
- my local mediator using https://github.com/hyperledger/aries-framework-javascript/releases/tag/0.0.60-unstable.0 ( as advised here https://github.com/hyperledger/aries-mobile-agent-react-native/issues/53#issuecomment-892504070 )

Now, I want to get credentials stored in my wallet app and later to present this to any party.

Are there public demo websites/endpoints that I can use to demo credentials storing and proof verification using this app?

or are there steps where I can run my Issuer and Verifier demo website?

Thanks

**Comment by manghuli** [comment]
You can use these two projects in tandem to create and issue credentials and perform proofs.

https://github.com/hyperledger/aries-acapy-plugin-toolbox
https://github.com/hyperledger/aries-toolbox

**Comment by xtrycatchx** [comment]
I managed to do a demo but only for Credential Issuance. For Python Cloud Agent to send a Proof Request, the mobile agent received it and do nothing, no interaction in the UI as well.

Also, for the Cloud Agent, it need to be ran with Aries Interop Profile 1.0

**Comment by WhiteSeasons** [comment]
> I managed to do a demo but only for Credential Issuance. For Python Cloud Agent to send a Proof Request, the mobile agent received it and do nothing, no interaction in the UI as well.
> 
> Also, for the Cloud Agent, it need to be ran with Aries Interop Profile 1.0

Hello ，can you share the demo , which can Interactive with the  mobile agent 。thanks

**Comment by xtrycatchx** [comment]
> Hello ，can you share the demo , which can Interactive with the  mobile agent 。thanks


You may check my screencast here [https://youtu.be/AomoHvw4lgc](https://youtu.be/AomoHvw4lgc)

**Comment by TimoGlastra** [comment]
This is really cool @xtrycatchx! Would it be okay to add this to the readme of the project? I think it can be valuable to others getting started

**Comment by xtrycatchx** [comment]
> This is really cool @xtrycatchx! Would it be okay to add this to the readme of the project? I think it can be valuable to others getting started

Yes, its okay 😎

**Comment by TimoGlastra** [comment]
Awesome :)

https://github.com/hyperledger/aries-mobile-agent-react-native/pull/74

**Comment by manghuli** [comment]
> I managed to do a demo but only for Credential Issuance. For Python Cloud Agent to send a Proof Request, the mobile agent received it and do nothing, no interaction in the UI as well.
> 
> Also, for the Cloud Agent, it need to be ran with Aries Interop Profile 1.0

Proofs aren't part of the app quite yet. I'm starting work on them today. I'll check back in once they get merged

**Comment by zhangbobo2023** [comment]
> > Hello ，can you share the demo , which can Interactive with the  mobile agent 。thanks
> 
> You may check my screencast here https://youtu.be/AomoHvw4lgc


I have run the demo according to screencast ，when scan the QR code，mobile app show the connection state ：requested，but faber agent no response，so i want to check the aca demo version，

 mobile agent ：main branch ，latest
 mediator：aries-framework-javascript/releases/tag/0.0.60-unstable.0
 aca demo ：main branch ，latest ？

 it's all right ?  thanks

**Comment by karimStekelenburg** [comment]
Closing this one as it seems stale. Reopen if needed.
