### ISSUE TITLE
Error when removing credential

### ISSUE THREAD

**Issue by thiagoromanos** [openwallet-foundation/bifold-wallet#705]
When I try to remove a credential from my wallet, I get the following error: 
`ERROR  TypeError: Cannot read property 'length' of undefined`
That message appears using a debug apk. The release one simply crashes.
If I close the app and reopen, the credential was removed.

**Comment by jleach** [comment]
Can't reproduce on iOS. Will try on Android.

**Comment by jleach** [comment]
Ok, can reproduce on iOS and Android. Will fix.
