### ISSUE TITLE
Support for AIP 2.0

### ISSUE THREAD

**Issue by xtrycatchx** [openwallet-foundation/bifold-wallet#73]
is support for the new Aries Interop Profile 2.0 planned for this project?

**Comment by TimoGlastra** [comment]
Yes it's on the roadmap to eventually support AIP2.0

Before we can start to implement this in the mobile agent, we should first add support for AIP2.0 to [Aries Framework JavaScript](https://github.com/hyperledger/aries-framework-javascript.git). We're actively discussing the road to AIP2.0 in the AFJ working group calls (See https://github.com/hyperledger/aries-framework-javascript#contributing for info on the time/place of the calls)

**Comment by xtrycatchx** [comment]
Thanks for this info
