### ISSUE TITLE
Run error on Windows

### ISSUE THREAD

**Issue by 0farah** [openwallet-foundation/bifold-wallet#743]
**When I try to run aries mobile agent react native on Windows, I got an error. 
I am tryin to run the app on my mobile so I am using "npm run android"
What cause of this problem and how can I fix it?**
![img](https://user-images.githubusercontent.com/73497199/236167368-9355b6f6-4f00-4f7f-a072-c0cc668578a7.png)
I got these details when I run it with --scan
> Configure project :
Evaluating root project 'aries-bifold' using build file 'C:\Users\f.bouali\projets\mobile\aries-mobile-agent-react-native\app\android\build.gradle'.
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.1.1/gradle-8.1.1.pom]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/8.1.1/gradle-8.1.1.pom]
Watched directory hierarchies: []

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'aries-bifold'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:8.1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.1.1/gradle-8.1.1.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/8.1.1/gradle-8.1.1.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'aries-bifold'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:8.1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.1.1/gradle-8.1.1.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/8.1.1/gradle-8.1.1.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s

    at makeError (C:\Users\f.bouali\projets\mobile\aries-mobile-agent-react-native\app\node_modules\execa\index.js:174:9)
    at C:\Users\f.bouali\projets\mobile\aries-mobile-agent-react-native\app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\f.bouali\projets\mobile\aries-mobile-agent-react-native\app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\f.bouali\projets\mobile\aries-mobile-agent-react-native\app\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.

**Comment by cvarjao** [comment]
The project no longer uses `npm`, we have switched to `yarn`:
https://github.com/hyperledger/aries-mobile-agent-react-native/blob/main/DEVELOPER.md#running-app-in-android-emulator-with-metro

**Comment by 0farah** [comment]
Well, still have issues with yarn @cvarjao 
I tried with "yarn workspace aries-bifold-app run android" and yet not running

**Comment by alberto-instnt** [comment]
@0farah Looks like you need to run these instructions from` /packages/legacy/` install packages with `yarn` then do: `yarn run prepare` and you should be all set. Finally just do `yarn start`

**Comment by smannathan** [comment]
yarn run prepare is throwing error, not sure how to transpile the code.

~/bifold/packages/legacy$ yarn run prepare
Usage Error: Couldn't find a script named "prepare".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
