### ISSUE TITLE
Merge common decline and reject modals into one component

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#747]
The CommonRejectModal and CommonDeclineModal do mostly the same function with a variation on wording and content so they should be merged into a single component.

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/767

**Comment by nodlesh** [comment]
@jleach could you move this to Done? Thanks.
