### ISSUE TITLE
ERROR when npm run ios on MacOS BigSur

### ISSUE THREAD

**Issue by ykare** [openwallet-foundation/bifold-wallet#77]
Hi, when I tried to run "npm run ios" on MacOS BigSur, I got the following error:

```
error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "8GUD26WFN3" with a private key was found. (in target 'AriesBifoldTests' from project 'AriesBifold')
error: Signing for "AriesBifold" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'AriesBifold' from project 'AriesBifold')

** BUILD FAILED **
```

Here is the version information:
npm: 7.23.0
node: 12.16.2
pod: 1.11.2
MacOS: 11.5.2

Thanks in advance.

Yoshiyuki Karezaki

**Comment by karimStekelenburg** [comment]
XCode and iOS require you to sign the code using an Apple developer account. Please refer to https://help.apple.com/xcode/mac/current/#/dev60b6fbbc7 for more information on this topic.

Closing this issue as it is not related to this project.
