### ISSUE TITLE
No provision record  found

### ISSUE THREAD

**Issue by WhiteSeasons** [openwallet-foundation/bifold-wallet#78]
![B954E8AB-CFD7-41f4-957B-67CA111D9C93](https://user-images.githubusercontent.com/87514220/133406777-66fc6553-5d4f-499a-84ac-d7e0779953e6.png)

when run the  android app， throw an indyError， walletItemNotFound。 

so how to solve， thanks。

**Comment by TimoGlastra** [comment]
Did you manage to fix the issue?

**Comment by JamesKEbert** [comment]
If I'm not mistaken I think this would be expected behavior since the first time the agent launches no mediator will have been configured and it will then proceed to create the connection & record?

**Comment by jleach** [comment]
As per todays Bifold WG call we're closing stale our otherwise dormant issues. Please re-open if its still relevant.
