### ISSUE TITLE
Stuck notification for connectionless proof requests

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#785]
Creating this issue to track a problem reported by one of our wider team. They think they go into this situation with a connectionless proof requests. They have a notification on their home screen indicating a proof request is in-flight but the status of the proof seems to be "done". May not be cleaned up at the AFJ level. They can not accept ore decline it. The screen shots are blue because its the BC Wallet themed version.

![Screenshot_20230525_133535_BC Wallet.jpg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/a482672d-2e4f-42cb-8337-a9bbcebdfd5e)

![Screenshot_20230525_133517_BC Wallet.jpg](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/74b78eef-ac5b-4ef2-b998-65c0bf8e5916)

**Comment by cvarjao** [comment]
This was an issue with the wallet showing the outgoing proof request what was generated via mobile verifier to another wallet

**Comment by hiteshgh** [comment]
Assigned to @wadeking98 to confirm if this was testing in " Test Flight " and if working close it
