### ISSUE TITLE
Deleting the mediator connection renders the wallet unusable

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#797]
With developer mode enabled you can delete the mediator connection. If this is done, the wallet becomes unusable next time it initializes. The following error message is displayed and cannot be dismissed:

![Screenshot 2023-05-31 at 7.59.13 AM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/852719b1-9dfc-4882-84a0-951c3b2c83fa)

**Comment by cvarjao** [comment]
closing stale issues
