### ISSUE TITLE
Change Wallet PIN/Key

### ISSUE THREAD

**Issue by cvarjao** [openwallet-foundation/bifold-wallet#805]
### Description of feature / user story
As a holder
I want to change my wallet PIN
so that I can keep my wallet secure with stronger PIN

### Notes
- Add item to the settings menu
- Refactor PIN create screen to work for PIN update
- Export wallet, import with new PIN/salt (new wallet key).  (Is there an easier way to do it?). 
  - Maybe Askar supports re-keying wallet
- Update keychain items
- If biometrics enabled, update secure storage

**Comment by hiteshgh** [comment]
Based on July 20 Planning , not a priority , so just add feature flag/PIN for now

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/921

**Comment by nodlesh** [comment]
Tested in build 1113 on both Android and iOS. 
Can someone close this? I cannot in this repo.
