### ISSUE TITLE
The app should display URLs properly in Chat messages

### ISSUE THREAD

**Issue by cvarjao** [openwallet-foundation/bifold-wallet#806]
### Description of feature / user story

As a contact, I want to be able to display links into a message so that I can link URLs.

A contact should be able to send a message containing a URL to another contact and, the recipient of the message should be able to click on the URL and have in open in the default browser on device.

### Acceptance Criteria

- [ ] URLs (`http:`, `https:`, `mailto:`) should be parsed out of messages and displayed properly;
- [ ] URLs should be touchable so that a user can interact with them;
- [ ] When touching a URL it should open in the default browser on device.
- [ ] The display of the URL should match the URLs format in the style guide.

### Wireframes or relevant image assets / links

n/a

### Relates to
- [Aries RFC 0095: Basic Message Protocol 1.0](https://github.com/hyperledger/aries-rfcs/tree/main/features/0095-basic-message)
- hyperledger/aries-rfcs#786

**Comment by knguyenBC** [comment]
URL does not match style guide. ALL links must be underlined. https://xd.adobe.com/view/eb9e0945-61d7-40ca-8e8e-bf4bd0c72934-becd/

**Comment by hiteshgh** [comment]
@wadeking98 - see comments from Kim above and advise

**Comment by wadeking98** [comment]
Resolved by: https://github.com/hyperledger/aries-mobile-agent-react-native/pull/952

**Comment by knguyenBC** [comment]
@wadeking98 @cvarjao I can't close the ticket but checked iOS and Android build 1174. Looks good.
