### ISSUE TITLE
Setup access to publish NPM packages

### ISSUE THREAD

**Issue by cvarjao** [openwallet-foundation/bifold-wallet#812]
- Package org/scope: `@aries-bifold`
- Admin/Owner Access (NPM accounts):
  - [hyperledger-ci](https://www.npmjs.com/~hyperledger-ci)
  - [hyperledger-lf](https://www.npmjs.com/~hyperledger-lf)
  - [cvarjao](https://www.npmjs.com/~cvarjao)

Notes:
- What is the process for acquiring an access token for automation? is it from `hyperledger-ci` account?

**Comment by ryjones** [comment]
@cvarjao `NPM_PUBLISH` is the name of the secret

**Comment by cvarjao** [comment]
Thanks @ryjones !
