### ISSUE TITLE
Proof request screen not dismissing after accepting a credential offer

### ISSUE THREAD

**Issue by jleach** [openwallet-foundation/bifold-wallet#849]
### Description of problem

When declining a proof request after accepting a credential the proof screen does not dismiss. It remains visible even though the proof was actually declined in the background. If the user presses the "Decline" button again, an error is presented as expected because the proof is already declined.

### Expected behavior

When the proof is declined the screen should be dismissed and the user should be returned to the home screen.

### Steps to reproduce

1. Start the [BC Showcase demo](https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca/digital-trust/showcase);
2. Proceed as Alice;
3. Scan the QR code and accept the credential;
4. Proceed to the proof examples, select the first / top example;
5. Scan the QR code;
4. One the presentation proof screen, decline the proof request;

The screen should disappear.

### Screenshots and/or log output

https://fullboarca-my.sharepoint.com/:v:/g/personal/jason_leach_fullboar_ca/EdnW-mrscP1JrzYrrIqWJAYB_YuTY74wj8YN2nXysY2q3Q?e=Z6Sw0p

### Environment
- [ ] Occurs on Android
- [x] Occurs on iOS

Build #:

1.0.9-975

Android Device Model: 

iOS Device Model: 

iPhone 14 Pro

### Workaround

Press the home button after you decline the credential

### Severity
- [ ] High
- [ ] Medium
- [x] Low

**Comment by cvarjao** [comment]
if I terminate/restart the app after getting the credential, then it works. Seems like something between getting/accepting a credential offer and rejecting a proof request is causing the problem

**Comment by jleach** [comment]
```console
 DEBUG  DEBUG: No response received.
 ERROR  The action 'NAVIGATE' with payload {"name":"Home"} was not handled by any navigator.

Do you have a screen named 'Home'?

If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator.

This is a development-only warning and won't be shown in production.
```
