### ISSUE TITLE
walletName undefined causing errors during connections

### ISSUE THREAD

**Issue by bryce-mcmath** [openwallet-foundation/bifold-wallet#871]
### Description of problem
Older wallets running the latest build will overwrite the default value of `walletName` with `undefined` causing errors during connections due to the label missing

### Expected behavior
The label should always be defined and the default value should not be overwritten with `undefined` during initialization

### Steps to reproduce
Complete onboarding with an older version of the wallet (pre-wallet naming PR), then switch to the latest version without wiping your storage. After reloading, try to make a connection.

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: 998

Android Device Model: 

iOS Device Model: 

### Workaround
N/A

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by hiteshgh** [comment]
assigned back to @bryce-mcmath to confirm if bug is fixed, if yes mark as closed
