### ISSUE TITLE
Add toggle on/off push notifications

### ISSUE THREAD

**Issue by hiteshgh** [openwallet-foundation/bifold-wallet#906]
####Description of feature / user story####

-As a user, I want to be able to toggle on/off push notifications so that I can control the number of notification I get in my phone

####Acceptance Criteria####

-

####Wireframes or relevant image assets / links####

**Comment by jamshale** [comment]
You can do this with app settings if you wish. Not sure if that's good enough.

If this is a requirement to have a UI element for it in the app I think this should probably be a ticket in the wrapper repo ( BC wallet ). None of the actual push notification implementation will be done in bifold so it doesn't make much sense to have a toggle button for it in this code.

**Comment by knguyenBC** [comment]
What would the UI element in the app do? Could you specify what sort of notifications you want to be pushed? Or can you simply turn on/off. At which case, the OS level setting should be fine.

**Comment by cvarjao** [comment]
we will close this ticket for now and track under #52
