### ISSUE TITLE
[Scan > Allow camera use] Empty screen is displayed if the user does not allow camera usage after tapping the Scan button from the Credentials list

### ISSUE THREAD

**Issue by AlexanderShenshin** [openwallet-foundation/bifold-wallet#914]
### Description of problem
There is an empty screen that appears if the user does not allow camera usage after tapping the Scan button from the Credentials list.

### Expected behavior

Previous screen (Credentails list) is open.

#### Precondition: Do not allow the app to use camera.

- Open the app.
- Tap the Credentials button in the bottom menu. => Credentials screen is open.
- Tap the Scan button. => Allow camera use screen is open.
- Tap the Not now button.
- Look at the results.

### Environment
- [x] Occurs on Android
- [x] Occurs on iOS

Build #: https://github.com/hyperledger/aries-mobile-agent-react-native/tree/db3f18af25f554cd5d616e977e08551b77791c09

Android Device Model: Pixel 4a / Android 11 

iOS Device Model: iPhone 12mini / iOS 16.4.1(a)

### Workaround

Go back using OS buttons or swipe.

### Severity
- [x] High
- [ ] Medium
- [ ] Low

**Comment by jp0707** [comment]
I am looking into this and would like to raise a PR soon. 
cc: @amanji , @jleach

**Comment by jleach** [comment]
> I am looking into this and would like to raise a PR soon.

🙏

**Comment by jp0707** [comment]
PR for this fix - https://github.com/hyperledger/aries-mobile-agent-react-native/pull/942
cc: @amanji , @jleach

**Comment by amanji** [comment]
Quick turnaround. Great work!

**Comment by jp0707** [comment]
We can close this issue.
