### ISSUE TITLE
bug(oca): attribute_categories should not be required

### ISSUE THREAD

**Issue by cvarjao** [openwallet-foundation/bifold-wallet#945]
As per [OCA spec](https://oca.colossi.network/specification/#label-overlay), `attribute_categories` is optional.

https://github.com/hyperledger/aries-mobile-agent-react-native/blob/e83ae93fa42fbb96ad4a805195323d31d1436b5f/packages/oca/src/interfaces/data/semantic/LabelOverlayData.interface.ts#L6C5-L6C5

**Comment by amanji** [comment]
Confirmed. Will make optional.
