### ISSUE TITLE
bug(oca): Deprecation of attr_character_encoding causes typescript error

### ISSUE THREAD

**Issue by cvarjao** [openwallet-foundation/bifold-wallet#947]
If it is deprecated, should we make it optional? or remove it since I don't think anybody is using it?

https://github.com/hyperledger/aries-mobile-agent-react-native/blob/e83ae93fa42fbb96ad4a805195323d31d1436b5f/packages/oca/src/interfaces/data/semantic/CharacterEncodingOverlayData.interface.ts#L5

**Comment by amanji** [comment]
I think the spec should be updated to use consistent naming. In the meantime, if it is causing errors we can make it optional.
