### ISSUE TITLE
[Camera Disclosure Modal] Camera access flow is not compliant with App Store guidelines

### ISSUE THREAD

**Issue by AlexanderShenshin** [openwallet-foundation/bifold-wallet#965]
Recently we were going through App Store review with our wallet app that uses Aries Bifold components.

Please see App Store review feedback about current camera access flow:

We noticed your app encourages or directs users to allow the app to access the camera. Specifically, your app directs the user to grant permission in the following way(s): 

- A message appears before the permission request, and to proceed users press a “Allow” button. Use words like "Continue" or "Next" on the button instead.
- A message appears before the permission request, and the user can close the message and delay the permission request with the “Not Allow” button. The user should always proceed to the permission request after the message. 

Permission requests give users control of their personal information. It is important to respect their decision about how their data is used.

#### Next Steps

To resolve this issue, please revise the permission request process in your app to not display messages before the permission request with inappropriate words on buttons and include an exit button on the message before the permission request.

If necessary, you may provide more information about why you are requesting permission before the request appears. If the user is trying to use a feature in your app that won't function without access to the camera, you may include a notification to inform the user and provide a link to the Settings app. 

#### Resources 

- Watch a video from App Store Review with [tips for doing more for users with less data](https://developer.apple.com/go/?id=ar-tips-3).
- Learn more about designing [appropriate permission requests](https://developer.apple.com/design/human-interface-guidelines/patterns/accessing-private-data/).

**Comment by AlexanderShenshin** [comment]
Screenshot of Camera Disclosure Modal from BC Wallet (we used a completely similar one):

![CameraDisclosureModalExample (Medium)](https://github.com/hyperledger/aries-mobile-agent-react-native/assets/93187809/e3f64a5b-d64b-4260-9f3e-dfa683c7c6a3)

**Comment by knguyenBC** [comment]
Good to know. We'll change label on the button from "Allow" to "Continue".

**Comment by nodlesh** [comment]
This can be closed, Verified that Allow is now Continue and regression tests have been changed look for Continue. 
@bryce-mcmath can you close this? I don't have access to do so.
